# Generated by Django 5.1.7 on 2025-03-29 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Airfield",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="airfield_photos/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Glider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("n_number", models.CharField(max_length=20, unique=True)),
                ("competition_number", models.CharField(blank=True, max_length=10)),
                ("seats", models.PositiveIntegerField(default=2)),
                (
                    "picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="glider_photos/"
                    ),
                ),
                (
                    "rental_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "max_rental_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Towplane",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("registration", models.CharField(max_length=50)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="towplane_photos/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Logsheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finalized", models.BooleanField(default=False)),
                (
                    "airfield",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="logsheet.airfield",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("log_date", "airfield")},
            },
        ),
        migrations.CreateModel(
            name="RevisionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revised_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True)),
                (
                    "logsheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="logsheet.logsheet",
                    ),
                ),
                (
                    "revised_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("launch_time", models.TimeField()),
                ("landing_time", models.TimeField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("field", models.CharField(max_length=100)),
                ("flight_type", models.CharField(max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "release_altitude",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "0 ft"),
                            (100, "100 ft"),
                            (200, "200 ft"),
                            (300, "300 ft"),
                            (400, "400 ft"),
                            (500, "500 ft"),
                            (600, "600 ft"),
                            (700, "700 ft"),
                            (800, "800 ft"),
                            (900, "900 ft"),
                            (1000, "1000 ft"),
                            (1100, "1100 ft"),
                            (1200, "1200 ft"),
                            (1300, "1300 ft"),
                            (1400, "1400 ft"),
                            (1500, "1500 ft"),
                            (1600, "1600 ft"),
                            (1700, "1700 ft"),
                            (1800, "1800 ft"),
                            (1900, "1900 ft"),
                            (2000, "2000 ft"),
                            (2100, "2100 ft"),
                            (2200, "2200 ft"),
                            (2300, "2300 ft"),
                            (2400, "2400 ft"),
                            (2500, "2500 ft"),
                            (2600, "2600 ft"),
                            (2700, "2700 ft"),
                            (2800, "2800 ft"),
                            (2900, "2900 ft"),
                            (3000, "3000 ft"),
                            (3100, "3100 ft"),
                            (3200, "3200 ft"),
                            (3300, "3300 ft"),
                            (3400, "3400 ft"),
                            (3500, "3500 ft"),
                            (3600, "3600 ft"),
                            (3700, "3700 ft"),
                            (3800, "3800 ft"),
                            (3900, "3900 ft"),
                            (4000, "4000 ft"),
                            (4100, "4100 ft"),
                            (4200, "4200 ft"),
                            (4300, "4300 ft"),
                            (4400, "4400 ft"),
                            (4500, "4500 ft"),
                            (4600, "4600 ft"),
                            (4700, "4700 ft"),
                            (4800, "4800 ft"),
                            (4900, "4900 ft"),
                            (5000, "5000 ft"),
                            (5100, "5100 ft"),
                            (5200, "5200 ft"),
                            (5300, "5300 ft"),
                            (5400, "5400 ft"),
                            (5500, "5500 ft"),
                            (5600, "5600 ft"),
                            (5700, "5700 ft"),
                            (5800, "5800 ft"),
                            (5900, "5900 ft"),
                            (6000, "6000 ft"),
                            (6100, "6100 ft"),
                            (6200, "6200 ft"),
                            (6300, "6300 ft"),
                            (6400, "6400 ft"),
                            (6500, "6500 ft"),
                            (6600, "6600 ft"),
                            (6700, "6700 ft"),
                            (6800, "6800 ft"),
                            (6900, "6900 ft"),
                            (7000, "7000 ft"),
                        ],
                        help_text="Release altitude in feet (0–7000 in 100ft steps)",
                        null=True,
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flights_as_instructor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pilot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flights_as_pilot",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tow_pilot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flights_as_tow_pilot",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "glider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="logsheet.glider",
                    ),
                ),
                (
                    "logsheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flights",
                        to="logsheet.logsheet",
                    ),
                ),
                (
                    "towplane",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="logsheet.towplane",
                    ),
                ),
            ],
        ),
    ]
