# Generated by Django 5.1.7 on 2025-03-28 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0001_initial"),
        ("members", "0026_rename_date_flightday_flight_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("launch_time", models.TimeField()),
                ("landing_time", models.TimeField(blank=True, null=True)),
                ("field", models.CharField(max_length=100)),
                ("flight_type", models.CharField(max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "glider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="members.glider",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flights_as_instructor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "logsheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flights",
                        to="logsheet.logsheet",
                    ),
                ),
                (
                    "pilot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flights_as_pilot",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tow_pilot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flights_as_tow_pilot",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
