# Generated by Django 5.1.7 on 2025-03-31 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="logsheet",
            name="assistant_duty_officer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"duty_officer": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="log_assistant_duty_officer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="logsheet",
            name="default_towplane",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="logsheet.towplane",
            ),
        ),
        migrations.AddField(
            model_name="logsheet",
            name="duty_instructor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"instructor": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="log_duty_instructor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="logsheet",
            name="duty_officer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"duty_officer": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="log_duty_officer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="logsheet",
            name="surge_instructor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"instructor": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="log_surge_instructor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="logsheet",
            name="surge_tow_pilot",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"towpilot": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="log_surge_tow_pilot",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="logsheet",
            name="tow_pilot",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"towpilot": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="log_tow_pilot",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
