# Generated by Django 5.2.6 on 2025-09-05 19:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glider',
            name='initial_hours',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Starting Hobbs/total time when electronic logging began (decimal hours).', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='towplane',
            name='initial_hours',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Starting Hobbs/total time when electronic logging began (decimal hours).', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
