# Generated by Django 5.2.6 on 2025-09-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0002_glider_initial_hours_towplane_initial_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenanceissue",
            name="report_date",
            field=models.DateField(),
        ),
    ]
