# Generated by Django 5.1.7 on 2025-03-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0002_flight"),
    ]

    operations = [
        migrations.AddField(
            model_name="logsheet",
            name="finalized",
            field=models.BooleanField(default=False),
        ),
    ]
