# Generated by Django 5.1.7 on 2025-04-01 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0002_logsheet_assistant_duty_officer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="passenger",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flights_as_passenger",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="passenger_name",
            field=models.CharField(
                blank=True,
                help_text="Name of passenger if not a member",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="logsheet",
            name="assistant_duty_officer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"assistant_duty_officer": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="log_assistant_duty_officer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
