# Generated by Django 5.2.6 on 2025-10-02 02:33

import utils.upload_entropy
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsheet', '0003_alter_maintenanceissue_report_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='airfield',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.upload_entropy.upload_airfield_photo),
        ),
        migrations.AlterField(
            model_name='glider',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.upload_entropy.upload_glider_photo),
        ),
        migrations.AlterField(
            model_name='towplane',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.upload_entropy.upload_towplane_photo),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['pilot'], name='logsheet_fl_pilot_i_8c6f5b_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['instructor'], name='logsheet_fl_instruc_7a7972_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['passenger'], name='logsheet_fl_passeng_92ffe2_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['logsheet'], name='logsheet_fl_logshee_9e2e5b_idx'),
        ),
    ]
