# Generated by Django 5.1.7 on 2025-04-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0004_towrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="rental_cost_actual",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="tow_cost_actual",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
