# Generated by Django 5.1.7 on 2025-03-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0004_revisionlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Towplane",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("registration", models.CharField(max_length=50)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="towplane_photos/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
