# Generated by Django 5.1.7 on 2025-03-28 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0005_towplane"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="towplane",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="logsheet.towplane",
            ),
        ),
    ]
