# Generated by Django 5.2.6 on 2025-10-09 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0005_glider_max_rental_hours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="glider",
            name="max_rental_hours",
        ),
    ]
