# Generated by Django 5.1.7 on 2025-04-01 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0005_flight_rental_cost_actual_flight_tow_cost_actual"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="split_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("even", "50/50"),
                    ("tow", "Tow Only"),
                    ("rental", "Rental Only"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="split_with",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shared_flights",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
