# Generated by Django 5.2.6 on 2025-10-10 00:54

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0006_remove_glider_max_rental_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="glider",
            name="next_100hr_due",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Cumulative hours at which next 100-hour inspection is due.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="glider",
            name="requires_100hr_inspection",
            field=models.BooleanField(
                default=False,
                help_text="Check if this glider requires 100-hour inspections.",
            ),
        ),
        migrations.AddField(
            model_name="towplane",
            name="next_100hr_due",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Tach time at which next 100-hour inspection is due.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="towplane",
            name="next_oil_change_due",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Tach time at which next oil change is due.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="towplane",
            name="oil_change_interval",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("50.0"),
                help_text="Hours between oil changes (default 50, but configurable per aircraft).",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="towplane",
            name="requires_100hr_inspection",
            field=models.BooleanField(
                default=False,
                help_text="Check if this towplane requires 100-hour inspections.",
            ),
        ),
    ]
