# Generated by Django 5.1.7 on 2025-03-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0006_flight_towplane"),
    ]

    operations = [
        migrations.CreateModel(
            name="Glider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("n_number", models.CharField(max_length=20, unique=True)),
                ("competition_number", models.CharField(blank=True, max_length=10)),
                ("seats", models.PositiveIntegerField(default=2)),
                (
                    "picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="glider_photos/"
                    ),
                ),
                (
                    "rental_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "max_rental_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
            ],
        ),
    ]
