# Generated by Django 5.1.7 on 2025-04-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0007_alter_flight_split_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("account", "On Account"), ("check", "Check")],
                max_length=10,
                null=True,
            ),
        ),
    ]
