# Generated by Django 5.2.8 on 2025-11-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0008_flight_logsheet_fl_towplan_f62a50_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="towplane",
            name="hourly_rental_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Hourly rental rate for non-towing flights (sightseeing, flight reviews, retrieval, etc.) in USD per hour.",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="towplanecloseout",
            name="rental_hours_chargeable",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Hours of towplane use to be charged as rental (non-towing flights like sightseeing, flight reviews, retrieval).",
                max_digits=4,
                null=True,
            ),
        ),
    ]
