# Generated by Django 5.1.7 on 2025-03-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0008_flight_release_altitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
