# Generated by Django 5.1.7 on 2025-04-01 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0008_flight_payment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="payment_method",
        ),
    ]
