# Generated by Django 5.1.7 on 2025-03-29 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0009_flight_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="glider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="logsheet.glider",
            ),
        ),
    ]
