# Generated by Django 5.2.8 on 2025-11-21 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0009_add_towplane_rental_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="towplanecloseout",
            name="rental_charged_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Member to be charged for towplane rental time (if any).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
