# Generated by Django 5.2.8 on 2025-11-22 16:18

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0010_add_towplane_rental_charged_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="TowplaneChargeScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this charging scheme (e.g., 'Pawnee Standard Rates')",
                        max_length=100,
                    ),
                ),
                (
                    "hookup_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Fixed fee charged for any tow, regardless of altitude ($0 if none)",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, falls back to global TowRate system",
                        db_index=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of this pricing scheme",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "towplane",
                    models.OneToOneField(
                        help_text="The towplane this charging scheme applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charge_scheme",
                        to="logsheet.towplane",
                    ),
                ),
            ],
            options={
                "verbose_name": "Towplane Charge Scheme",
                "verbose_name_plural": "Towplane Charge Schemes",
                "ordering": ["towplane__name"],
            },
        ),
        migrations.CreateModel(
            name="TowplaneChargeTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "altitude_start",
                    models.PositiveIntegerField(
                        help_text="Starting altitude for this tier (feet, inclusive)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "altitude_end",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Ending altitude for this tier (feet, exclusive). Leave blank for unlimited.",
                        null=True,
                    ),
                ),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("flat", "Flat Rate (charge once for entire tier)"),
                            (
                                "per_1000ft",
                                "Per 1000 feet (charge per 1000ft increment)",
                            ),
                            ("per_100ft", "Per 100 feet (charge per 100ft increment)"),
                        ],
                        default="per_1000ft",
                        help_text="How to calculate charges for this altitude range",
                        max_length=20,
                    ),
                ),
                (
                    "rate_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Rate amount in USD (interpretation depends on rate_type)",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, this tier is ignored in calculations",
                        db_index=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional description (e.g., 'Base tow to pattern altitude')",
                        max_length=200,
                    ),
                ),
                (
                    "charge_scheme",
                    models.ForeignKey(
                        help_text="The charge scheme this tier belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charge_tiers",
                        to="logsheet.towplanechargescheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Towplane Charge Tier",
                "verbose_name_plural": "Towplane Charge Tiers",
                "ordering": ["charge_scheme", "altitude_start"],
                "unique_together": {("charge_scheme", "altitude_start")},
            },
        ),
    ]
