# Generated by Django 5.1.7 on 2025-04-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0010_logsheetpayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logsheetpayment",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("account", "On Account"),
                    ("check", "Check"),
                    ("zelle", "Zelle"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
