# Generated by Django 5.1.7 on 2025-03-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0010_alter_flight_glider"),
    ]

    operations = [
        migrations.CreateModel(
            name="Airfield",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="airfield_photos/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
