# Generated by Django 5.1.7 on 2025-03-29 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0011_airfield"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Airfield",
        ),
    ]
