# Generated by Django 5.2.8 on 2025-11-24 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0011_add_towplane_charging_models"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TowRate",
        ),
    ]
