# Generated by Django 5.2.8 on 2025-11-26 21:57

from django.db import migrations, models

import utils.upload_entropy


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0012_remove_towrate_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="glider",
            name="photo_medium",
            field=models.ImageField(
                blank=True,
                help_text="150x150 square thumbnail (auto-generated)",
                null=True,
                upload_to=utils.upload_entropy.upload_glider_photo_medium,
            ),
        ),
        migrations.AddField(
            model_name="glider",
            name="photo_small",
            field=models.ImageField(
                blank=True,
                help_text="100x100 square thumbnail (auto-generated)",
                null=True,
                upload_to=utils.upload_entropy.upload_glider_photo_small,
            ),
        ),
        migrations.AddField(
            model_name="towplane",
            name="photo_medium",
            field=models.ImageField(
                blank=True,
                help_text="150x150 square thumbnail (auto-generated)",
                null=True,
                upload_to=utils.upload_entropy.upload_towplane_photo_medium,
            ),
        ),
        migrations.AddField(
            model_name="towplane",
            name="photo_small",
            field=models.ImageField(
                blank=True,
                help_text="100x100 square thumbnail (auto-generated)",
                null=True,
                upload_to=utils.upload_entropy.upload_towplane_photo_small,
            ),
        ),
    ]
