# Generated by Django 5.1.7 on 2025-04-02 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0012_logsheetcloseout_towplanecloseout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="towplanecloseout",
            name="towplane",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="logsheet.towplane"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="towplanecloseout",
            unique_together={("logsheet", "towplane")},
        ),
    ]
