# Generated by Django 5.1.7 on 2025-03-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0012_delete_airfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="Airfield",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="airfield_photos/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
