# Generated by Django 5.1.7 on 2025-04-02 03:11

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0013_alter_towplanecloseout_towplane_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logsheetcloseout",
            name="equipment_issues",
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name="logsheetcloseout",
            name="operations_summary",
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name="logsheetcloseout",
            name="safety_issues",
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
