# Generated by Django 5.2.8 on 2025-11-26 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0013_add_equipment_photo_thumbnails"),
        ("logsheet", "0013_add_payment_indexes"),
    ]

    operations = []
