# Generated by Django 5.1.7 on 2025-04-02 03:56

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0014_alter_logsheetcloseout_equipment_issues_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="towplanecloseout",
            name="notes",
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
