# Generated by Django 5.2.9 on 2025-12-12 03:18

from django.db import migrations, models

import utils.upload_entropy


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0014_merge_20251126_1811"),
    ]

    operations = [
        migrations.AlterField(
            model_name="glider",
            name="photo_medium",
            field=models.ImageField(
                blank=True,
                help_text="150x150 square thumbnail. Auto-generated when photo is uploaded via admin.",
                null=True,
                upload_to=utils.upload_entropy.upload_glider_photo_medium,
            ),
        ),
        migrations.AlterField(
            model_name="glider",
            name="photo_small",
            field=models.ImageField(
                blank=True,
                help_text="100x100 square thumbnail. Auto-generated when photo is uploaded via admin.",
                null=True,
                upload_to=utils.upload_entropy.upload_glider_photo_small,
            ),
        ),
        migrations.AlterField(
            model_name="towplane",
            name="photo_medium",
            field=models.ImageField(
                blank=True,
                help_text="150x150 square thumbnail. Auto-generated when photo is uploaded via admin.",
                null=True,
                upload_to=utils.upload_entropy.upload_towplane_photo_medium,
            ),
        ),
        migrations.AlterField(
            model_name="towplane",
            name="photo_small",
            field=models.ImageField(
                blank=True,
                help_text="100x100 square thumbnail. Auto-generated when photo is uploaded via admin.",
                null=True,
                upload_to=utils.upload_entropy.upload_towplane_photo_small,
            ),
        ),
    ]
