# Generated by Django 5.2.9 on 2025-12-16 02:33

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "logsheet",
            "0015_alter_glider_photo_medium_alter_glider_photo_small_and_more",
        ),
        ("siteconfig", "0023_add_chargeable_items_and_retrieve_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="free_rental",
            field=models.BooleanField(
                default=False,
                help_text="No charge for glider rental (e.g., post-maintenance check flight, club-authorized free flight)",
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="free_tow",
            field=models.BooleanField(
                default=False,
                help_text="No charge for the aerotow (e.g., post-maintenance check flight, club-authorized free flight)",
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="is_retrieve",
            field=models.BooleanField(
                default=False,
                help_text="This is a retrieve flight (ferrying a glider back after a landout)",
            ),
        ),
        migrations.CreateModel(
            name="MemberCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Quantity (supports decimals for tach time, e.g., 1.8 hours)",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per unit at time of charge (snapshot, won't change if catalog price updates)",
                        max_digits=8,
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total charge (quantity × unit_price)",
                        max_digits=10,
                    ),
                ),
                ("date", models.DateField(help_text="Date the charge was applied")),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes about this charge"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chargeable_item",
                    models.ForeignKey(
                        help_text="Item or service being charged",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="siteconfig.chargeableitem",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        help_text="Member who entered this charge",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="charges_entered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "logsheet",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to logsheet (charges tied to finalized logsheets are locked)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="member_charges",
                        to="logsheet.logsheet",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Member being charged",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="misc_charges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Charge",
                "verbose_name_plural": "Member Charges",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["member", "date"], name="logsheet_me_member__11de0d_idx"
                    ),
                    models.Index(
                        fields=["logsheet"], name="logsheet_me_logshee_9ac60b_idx"
                    ),
                ],
            },
        ),
    ]
