# Generated by Django 5.1.7 on 2025-04-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0015_alter_towplanecloseout_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="towplanecloseout",
            name="end_tach",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="towplanecloseout",
            name="start_tach",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
