# Generated by Django 5.2.9 on 2025-12-16 04:57

import datetime
from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0016_add_chargeable_items_and_retrieve_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membercharge",
            name="date",
            field=models.DateField(
                default=datetime.date.today, help_text="Date the charge was applied"
            ),
        ),
        migrations.AlterField(
            model_name="membercharge",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total charge (quantity × unit_price)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="membercharge",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price per unit at time of charge (snapshot, won't change if catalog price updates)",
                max_digits=8,
                null=True,
            ),
        ),
    ]
