# Generated by Django 5.1.7 on 2025-04-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0016_alter_towplanecloseout_end_tach_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="launch_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
