# Generated by Django 5.1.7 on 2025-04-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0017_alter_flight_launch_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="guest_instructor_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="flight",
            name="guest_pilot_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="flight",
            name="guest_towpilot_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="flight",
            name="launch_method",
            field=models.CharField(
                choices=[
                    ("tow", "Towplane"),
                    ("winch", "Winch"),
                    ("self", "Self-Launch"),
                    ("other", "Other"),
                ],
                default="tow",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="legacy_instructor_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="flight",
            name="legacy_passenger_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="flight",
            name="legacy_pilot_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="flight",
            name="legacy_towpilot_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
