# Generated by Django 5.2.9 on 2026-01-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0017_add_defaults_and_nullable_to_membercharge"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="maintenancedeadline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("glider__isnull", True), ("towplane__isnull", True), _negated=True
                ),
                name="maintenance_deadline_must_have_aircraft",
            ),
        ),
    ]
