# Generated by Django 5.1.7 on 2025-04-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0019_alter_flight_legacy_instructor_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="guest_instructor_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="flight",
            name="guest_pilot_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="flight",
            name="guest_towpilot_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
