# Generated by Django 5.2.12 on 2026-04-08 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "logsheet",
            "0020_commercialticket_commercialride_commercialpassenger_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="commercial_ride",
            field=models.BooleanField(
                default=False,
                help_text="Marks this flight as a commercial ride tracked by ticket.",
            ),
        ),
        migrations.AlterField(
            model_name="commercialride",
            name="flight",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commercial_ride_record",
                to="logsheet.flight",
            ),
        ),
    ]
