# Generated by Django 5.1.7 on 2025-04-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0020_alter_flight_guest_instructor_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="towplanecloseout",
            name="tach_time",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
