# Generated by Django 5.2.14 on 2026-05-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0021_flight_commercial_ride_alter_commercialride_flight"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="instruction_fee_actual",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
