# Generated by Django 5.1.7 on 2025-04-11 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0021_towplanecloseout_tach_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="field",
        ),
    ]
