# Generated by Django 5.2.11 on 2026-02-13 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0023_member_is_stats_monger"),
        ("logsheet", "0023_add_flight_logsheet_id_id_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatsDumpOutbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "result_file",
                    models.FileField(blank=True, upload_to="exports/stats_dumps/"),
                ),
                ("result_filename", models.CharField(blank=True, max_length=255)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stats_dump_exports",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "ordering": ["-queued_at"],
            },
        ),
    ]
