# Generated by Django 5.2.14 on 2026-07-29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0024_statsdumpoutbox"),
        ("members", "0024_align_stats_monger_column_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightSplitRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("split_type", models.CharField(choices=[("even", "50/50"), ("tow", "Tow Only"), ("rental", "Rental Only"), ("full", "Full Cost")], max_length=10)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("accepted", "Accepted"), ("rejected", "Rejected"), ("cancelled", "Cancelled")], default="pending", max_length=10)),
                ("reason", models.TextField(blank=True)),
                ("allocation_version", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("flight", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="split_requests", to="logsheet.flight")),
                ("requested_member", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="received_flight_split_requests", to="members.member")),
                ("requester", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="made_flight_split_requests", to="members.member")),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(condition=models.Q(("status", "pending")), fields=("flight",), name="one_pending_split_request_per_flight"),
                ],
            },
        ),
    ]
