# Generated by Django 5.1.7 on 2025-04-19 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0025_maintenancedeadline_aircraftmeister_maintenanceissue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aircraftmeister",
            name="aircraft_n_number",
        ),
        migrations.RemoveField(
            model_name="aircraftmeister",
            name="aircraft_type",
        ),
        migrations.RemoveField(
            model_name="maintenancedeadline",
            name="aircraft_n_number",
        ),
        migrations.RemoveField(
            model_name="maintenancedeadline",
            name="aircraft_type",
        ),
        migrations.RemoveField(
            model_name="maintenanceissue",
            name="aircraft_n_number",
        ),
        migrations.RemoveField(
            model_name="maintenanceissue",
            name="aircraft_type",
        ),
        migrations.AddField(
            model_name="aircraftmeister",
            name="glider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="logsheet.glider",
            ),
        ),
        migrations.AddField(
            model_name="aircraftmeister",
            name="towplane",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="logsheet.towplane",
            ),
        ),
        migrations.AddField(
            model_name="maintenancedeadline",
            name="glider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="logsheet.glider",
            ),
        ),
        migrations.AddField(
            model_name="maintenancedeadline",
            name="towplane",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="logsheet.towplane",
            ),
        ),
        migrations.AddField(
            model_name="maintenanceissue",
            name="glider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="logsheet.glider",
            ),
        ),
        migrations.AddField(
            model_name="maintenanceissue",
            name="towplane",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="logsheet.towplane",
            ),
        ),
    ]
