# Generated by Django 5.1.7 on 2025-04-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0026_remove_aircraftmeister_aircraft_n_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="glider",
            name="club_owned",
            field=models.BooleanField(default=True),
        ),
    ]
