# Generated by Django 5.2.15 on 2026-08-16 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0029_flight_client_token_idempotency"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="flight",
            new_name="logsheet_fl_logshee_3a0b41_idx",
            old_name="logsheet_fl_logshee_25df4a_idx",
        ),
    ]
