# Generated by Django 5.1.7 on 2025-04-22 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0029_alter_logsheetpayment_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceissue",
            name="logsheet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="logsheet.logsheet",
            ),
        ),
    ]
