# Generated by Django 5.1.7 on 2025-04-22 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0030_maintenanceissue_logsheet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenanceissue",
            name="logsheet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_issues",
                to="logsheet.logsheet",
            ),
        ),
    ]
