# Generated by Django 5.1.7 on 2025-04-25 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0031_alter_maintenanceissue_logsheet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="towplane",
            old_name="registration",
            new_name="n_number",
        ),
    ]
