# Generated by Django 5.2.15 on 2026-09-07 02:36

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0032_logsheetguestpayment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TowplaneRentalCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Hours of non-towing usage charged to this member.",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                ("notes", tinymce.models.HTMLField(blank=True)),
                (
                    "closeout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_charges",
                        to="logsheet.towplanecloseout",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="towplane_rental_charges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["member__last_name", "member__first_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("closeout", "member"),
                        name="unique_rental_charge_per_closeout_member",
                    )
                ],
            },
        ),
    ]
