# Generated by Django 5.1.7 on 2025-04-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0032_rename_registration_towplane_n_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="towplane",
            name="club_owned",
            field=models.BooleanField(default=False),
        ),
    ]
