# Generated by Django 5.1.7 on 2025-04-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0033_towplane_club_owned"),
    ]

    operations = [
        migrations.AddField(
            model_name="towplane",
            name="make",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="towplane",
            name="model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
