# Generated by Django 5.2.15 on 2026-09-09 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0034_backfill_towplanerentalcharge"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogsheetTowplane",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_tach",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Starting tach reading for the day. Pre-populated from the prior flying day's ending tach when the row is first created.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "logsheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_towplanes",
                        to="logsheet.logsheet",
                    ),
                ),
                (
                    "tow_pilot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tow pilot scheduled on this towplane for the day.",
                        limit_choices_to={"towpilot": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logsheet_towplane_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "towplane",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logsheet.towplane",
                    ),
                ),
            ],
            options={
                "ordering": ["towplane__n_number"],
                "indexes": [
                    models.Index(
                        fields=["towplane", "logsheet"],
                        name="logsheet_lo_towplan_d8a18f_idx",
                    )
                ],
                "unique_together": {("logsheet", "towplane")},
            },
        ),
    ]
