# Generated by Django 5.1.7 on 2025-04-25 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0034_towplane_make_towplane_model"),
    ]

    operations = [
        migrations.RenameField(
            model_name="glider",
            old_name="picture",
            new_name="photo",
        ),
    ]
