# Generated by Django 5.2.15 on 2026-09-11 02:43

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0035_add_logsheetscheduledtowplane"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logsheettowplane",
            name="start_tach",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Starting tach reading for the day. Pre-populated from the prior flying day's ending tach when the row is first created.",
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
