# Generated by Django 5.2.15 on 2026-09-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0037_towplanecloseout_start_tach_auto_derived_from_roster"),
    ]

    operations = [
        migrations.AddField(
            model_name="towplanecloseout",
            name="start_tach_manually_cleared",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="towplanecloseout",
            name="start_tach_auto_derived_from_roster",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
