# Generated by Django 5.2.14 on 2026-07-26 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_ledger_entry_immutability"),
        (
            "logsheet",
            "0024_statsdumpoutbox",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgerentry",
            name="flight",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="billing_entries",
                to="logsheet.flight",
            ),
        ),
        migrations.CreateModel(
            name="FlightChargeSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tow_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("rental_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "instruction_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("allocation_rule", models.CharField(max_length=50)),
                ("allocation_version", models.PositiveIntegerField()),
                ("allocation_snapshot", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "billed_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="logsheet.flight",
                    ),
                ),
                (
                    "ledger_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flight_snapshot",
                        to="billing.ledgerentry",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("tow_amount__gte", 0),
                            ("rental_amount__gte", 0),
                            ("instruction_amount__gte", 0),
                            ("total_amount__gt", 0),
                        ),
                        name="billing_snapshot_amounts_valid",
                    )
                ],
            },
        ),
    ]
