# Generated by Django 5.2.15 on 2026-08-22 21:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0009_alter_ledgerentry_kind"),
        ("logsheet", "0032_logsheetguestpayment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind", "guest_remittance"),
                    ("remits__isnull", True),
                    _connector="OR",
                ),
                name="billing_remits_only_guest_remittance",
            ),
        ),
    ]
