# Generated by Django 5.2.6 on 2025-09-10 21:03

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepagecontent",
            name="content",
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
