# Generated by Django 5.2.6 on 2025-10-02 02:33

import utils.upload_entropy
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_remove_homepagecontent_image_homepageimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageimage',
            name='image',
            field=models.ImageField(upload_to=utils.upload_entropy.upload_homepage_gallery),
        ),
    ]
