# Generated by Django 5.2.6 on 2025-10-16 02:42

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models

import cms.models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0005_alter_homepagecontent_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL path for this page, e.g. 'club-documents', 'bylaws', etc.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("content", tinymce.models.HTMLField(blank=True)),
                ("is_public", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent directory (for subdirectories)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="cms.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "CMS Page",
                "verbose_name_plural": "CMS Pages",
                "unique_together": {("parent", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to=cms.models.upload_document_to)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="cms.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "CMS Document",
                "verbose_name_plural": "CMS Documents",
            },
        ),
    ]
