# Generated by Django 5.2.6 on 2025-10-29 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0007_sitefeedback"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Visitor's full name", max_length=100),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Visitor's email address for follow-up",
                        max_length=254,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Optional phone number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Brief subject line for the inquiry", max_length=200
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="Detailed message from the visitor"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address for spam prevention",
                        null=True,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("read", "Read"),
                            ("responded", "Responded"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes for member managers",
                        null=True,
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Member who handled this inquiry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Visitor Contact",
                "verbose_name_plural": "Visitor Contacts",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
