# Generated by Django 5.2.8 on 2025-11-13 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0008_visitorcontact"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageRolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_name",
                    models.CharField(
                        choices=[
                            ("instructor", "Instructor"),
                            ("towpilot", "Towpilot"),
                            ("duty_officer", "Duty Officer"),
                            ("assistant_duty_officer", "Assistant Duty Officer"),
                            ("secretary", "Secretary"),
                            ("treasurer", "Treasurer"),
                            ("webmaster", "Webmaster"),
                            ("director", "Director"),
                            ("member_manager", "Member Manager"),
                            ("rostermeister", "Rostermeister"),
                        ],
                        help_text="Member role required to access this page",
                        max_length=30,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="cms.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Role Permission",
                "verbose_name_plural": "Page Role Permissions",
                "unique_together": {("page", "role_name")},
            },
        ),
    ]
