# Generated by Django 5.2.8 on 2025-11-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0009_add_page_role_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagerolepermission",
            name="role_name",
            field=models.CharField(
                choices=[
                    ("active_member", "Any Active Member"),
                    ("instructor", "Instructor"),
                    ("towpilot", "Towpilot"),
                    ("duty_officer", "Duty Officer"),
                    ("assistant_duty_officer", "Assistant Duty Officer"),
                    ("secretary", "Secretary"),
                    ("treasurer", "Treasurer"),
                    ("webmaster", "Webmaster"),
                    ("director", "Director"),
                    ("member_manager", "Member Manager"),
                    ("rostermeister", "Rostermeister"),
                ],
                help_text="Member role required to access this page",
                max_length=30,
            ),
        ),
    ]
