# Generated by Django 5.2.8 on 2025-11-20 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0010_add_active_member_role_choice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["title", "file"],
                "verbose_name": "CMS Document",
                "verbose_name_plural": "CMS Documents",
            },
        ),
    ]
