# Generated by Django 5.2.8 on 2025-11-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0011_add_document_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitefeedback",
            name="referring_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="URL path of the page where feedback was submitted from",
                max_length=500,
            ),
        ),
    ]
