# Generated by Django 5.2.9 on 2026-01-14 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0012_change_referring_url_to_charfield"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PageMemberPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Member granted access to this page",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cms_page_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_permissions",
                        to="cms.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Member Permission",
                "verbose_name_plural": "Page Member Permissions",
                "unique_together": {("page", "member")},
            },
        ),
    ]
