# Generated by Django 5.2.9 on 2026-01-24 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0013_add_page_member_permission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagememberpermission",
            name="member",
            field=models.ForeignKey(
                help_text=(
                    "Member granted EDIT access to this page. Applies in Django admin for "
                    "public and private pages, and in the in-site editor for private pages "
                    "(also granting VIEW access there)."
                ),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cms_page_permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
