# Generated by Django 5.2.9 on 2026-01-25 03:25

from django.db import migrations, models

import utils.upload_entropy


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0014_update_pagememberpermission_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                help_text="Banner image displayed at top of page with parallax effect. Recommended size: 1920x600px.",
                null=True,
                upload_to=utils.upload_entropy.upload_cms_banner,
            ),
        ),
    ]
