# Generated by Django 5.2.9 on 2026-02-03 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import utils.upload_entropy


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0015_add_banner_image_to_page"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                help_text="Banner image displayed at top of page with parallax effect. The full image will be shown without cropping - recommended dimensions: 1920x300px (desktop), or any wide panoramic image with 6:1 or 5:1 aspect ratio. Banner height: 300px desktop, 200px tablet, 150px mobile.",
                null=True,
                upload_to=utils.upload_entropy.upload_cms_banner,
            ),
        ),
        migrations.AlterField(
            model_name="pagememberpermission",
            name="member",
            field=models.ForeignKey(
                help_text="Member granted EDIT access to this page. Applies in Django admin and the CMS UI (site editor) for both public and private pages. The Edit button will appear for this member on pages they're assigned to. For private pages, this also grants VIEW access wherever Page.can_user_access() is used.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cms_page_permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
