# Generated by Django 5.2.9 on 2026-02-03 03:42

from django.db import migrations, models

import utils.upload_entropy


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0015_add_banner_image_to_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                help_text="Banner image displayed at top of the page with a parallax effect. The image is scaled to fit within the banner area to minimize cropping; slight vertical clipping may still occur due to the parallax implementation and fixed banner height. Depending on screen size and aspect ratio, empty space (letterboxing) may appear above/below or to the sides. Recommended source size is at least 1920x300px (desktop) or any wide panoramic image around a 6:1–5:1 aspect ratio. Approximate maximum banner height: 300px desktop, 200px tablet, 150px mobile (very tall or narrow images will have more of their height hidden outside the visible banner area).",
                null=True,
                upload_to=utils.upload_entropy.upload_cms_banner,
            ),
        ),
    ]
