# Generated by Django 5.2.11 on 2026-02-10 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0016_update_banner_and_permission_help_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagememberpermission",
            name="member",
            field=models.ForeignKey(
                help_text="Member granted EDIT access to this page. Applies in Django admin and the CMS UI (site editor) for both public and private pages. The Edit button will appear for this member on pages they're assigned to. For private pages, this also grants VIEW access wherever Page.can_user_access() is used.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cms_page_permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
