# Generated by Django 5.2.11 on 2026-03-11 03:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0017_alter_pagememberpermission_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="navbar_rank",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Order in the Resources drawer when promoted. Lower ranks appear first (1-100).",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="navbar_title",
            field=models.CharField(
                blank=True,
                help_text="Optional display title in the Resources drawer. If blank, page title is used.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="promote_to_navbar",
            field=models.BooleanField(
                default=False,
                help_text="Promote this page into the top navbar Resources drawer. Only webmasters and superusers may change this setting.",
            ),
        ),
    ]
