# Generated by Django 5.2.17 on 2026-09-30 22:38

from django.db import migrations, models

import cms.models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0020_document_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalPdfCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2000, unique=True)),
                (
                    "file",
                    models.FileField(upload_to=cms.models.upload_external_pdf_cache_to),
                ),
                ("content_hash", models.CharField(max_length=64)),
                ("size_bytes", models.BigIntegerField()),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "External PDF Cache Entry",
                "verbose_name_plural": "External PDF Cache Entries",
            },
        ),
    ]
