# Generated by Django 5.2.6 on 2025-09-04 23:54

import django.db.models.deletion
import tinymce.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qnum', models.IntegerField(primary_key=True, serialize=False)),
                ('question_text', tinymce.models.HTMLField()),
                ('option_a', tinymce.models.HTMLField()),
                ('option_b', tinymce.models.HTMLField()),
                ('option_c', tinymce.models.HTMLField()),
                ('option_d', tinymce.models.HTMLField()),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explanation', tinymce.models.HTMLField(blank=True)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('media', models.FileField(blank=True, help_text='Optional image or file attachment for the question', null=True, upload_to='written_test_media/')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Member who last updated this question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_questions', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(db_column='code', on_delete=django.db.models.deletion.CASCADE, to='knowledgetest.questioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='WrittenTestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('pass_percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Minimum score (in %) required to pass', max_digits=5)),
                ('time_limit', models.DurationField(blank=True, help_text='Optional time limit for the test', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_written_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WrittenTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('score_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('time_taken', models.DurationField(blank=True, help_text='Duration student took to complete the test', null=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_written_tests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='written_test_attempts', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='knowledgetest.writtentesttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='WrittenTestTemplateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgetest.question')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgetest.writtentesttemplate')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('template', 'question')},
            },
        ),
        migrations.AddField(
            model_name='writtentesttemplate',
            name='questions',
            field=models.ManyToManyField(related_name='templates', through='knowledgetest.WrittenTestTemplateQuestion', to='knowledgetest.question'),
        ),
        migrations.CreateModel(
            name='WrittenTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledgetest.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='knowledgetest.writtentestattempt')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.CreateModel(
            name='WrittenTestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_written_tests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_written_tests', to=settings.AUTH_USER_MODEL)),
                ('attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledgetest.writtentestattempt')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='knowledgetest.writtentesttemplate')),
            ],
            options={
                'unique_together': {('template', 'student')},
            },
        ),
    ]
