# Generated by Django 5.1.7 on 2025-05-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledgetest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyQuestion",
            fields=[
                ("qnum", models.IntegerField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=8)),
                ("question", models.TextField()),
                ("a", models.TextField()),
                ("b", models.TextField()),
                ("c", models.TextField()),
                ("d", models.TextField()),
                ("answer", models.CharField(max_length=2)),
                ("explanation", models.TextField(blank=True)),
                ("lastupdated", models.DateField(null=True)),
                ("updatedby", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "db_table": "test_contents",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LegacyQuestionCategory",
            fields=[
                (
                    "qcode",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "qcodes",
                "managed": False,
            },
        ),
    ]
