# Generated by Django 5.2.6 on 2025-10-02 02:33

import utils.upload_entropy
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgetest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='media',
            field=models.FileField(blank=True, help_text='Optional image or file attachment for the question', null=True, upload_to=utils.upload_entropy.upload_written_test_media),
        ),
    ]
