# Generated by Django 5.1.7 on 2025-05-21 01:28

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knowledgetest", "0002_legacyquestion_legacyquestioncategory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LegacyQuestion",
        ),
        migrations.DeleteModel(
            name="LegacyQuestionCategory",
        ),
        migrations.AlterField(
            model_name="question",
            name="explanation",
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_a",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_b",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_c",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_d",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=tinymce.models.HTMLField(),
        ),
    ]
