# Generated by Django 5.2.6 on 2025-10-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledgetest", "0002_alter_question_media"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the test preset (e.g., 'ASK21', 'PW5', 'Duty Officer')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of what this preset is for",
                    ),
                ),
                (
                    "category_weights",
                    models.JSONField(
                        default=dict,
                        help_text="Dictionary mapping question category codes to the number of questions to include",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this preset is available for creating new tests",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Test Preset",
                "verbose_name_plural": "Test Presets",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
