# Generated by Django 5.1.7 on 2025-05-21 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "knowledgetest",
            "0003_delete_legacyquestion_delete_legacyquestioncategory_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Member who last updated this question",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
