# Generated by Django 5.2.6 on 2025-10-02 02:33

import utils.upload_entropy
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubqualificationtype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=utils.upload_entropy.upload_quals_icon),
        ),
        migrations.AddIndex(
            model_name='groundinstruction',
            index=models.Index(fields=['student'], name='instructors_student_f745bb_idx'),
        ),
        migrations.AddIndex(
            model_name='groundinstruction',
            index=models.Index(fields=['instructor'], name='instructors_instruc_3d776f_idx'),
        ),
        migrations.AddIndex(
            model_name='groundinstruction',
            index=models.Index(fields=['date'], name='instructors_date_574b76_idx'),
        ),
        migrations.AddIndex(
            model_name='instructionreport',
            index=models.Index(fields=['student'], name='instructors_student_2c5fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='instructionreport',
            index=models.Index(fields=['instructor'], name='instructors_instruc_c93a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='instructionreport',
            index=models.Index(fields=['report_date'], name='instructors_report__4fa5da_idx'),
        ),
        migrations.AddIndex(
            model_name='instructionreport',
            index=models.Index(fields=['student', 'instructor', 'report_date'], name='instructors_student_251b7a_idx'),
        ),
    ]
