# Generated by Django 5.2.9 on 2025-12-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0002_alter_clubqualificationtype_icon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groundlessonscore",
            name="score",
            field=models.CharField(
                choices=[
                    ("1", "1 - Introduced (Discussed/Demonstrated)"),
                    ("2", "2 - Practiced"),
                    ("3", "3 - Solo Standard"),
                    ("4", "4 - Checkride Standard"),
                    ("!", "! - Needs Attention"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="lessonscore",
            name="score",
            field=models.CharField(
                choices=[
                    ("1", "1 - Introduced (Discussed/Demonstrated)"),
                    ("2", "2 - Practiced"),
                    ("3", "3 - Solo Standard"),
                    ("4", "4 - Checkride Standard"),
                    ("!", "! - Needs Attention"),
                ],
                max_length=2,
            ),
        ),
    ]
