# Generated by Django 5.1.7 on 2025-04-12 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0002_syllabusdocument_trainingphase_traininglesson_phase"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="traininglesson",
            options={"ordering": ["code"]},
        ),
    ]
