# Generated by Django 5.2.9 on 2026-01-27 23:59

import re

from django.db import migrations, models


def generate_sort_key(code: str) -> str:
    """
    Generate a sort key from a lesson code for natural/version-number sorting.

    Handles nested number formats like "1.10" by zero-padding each segment.
    Examples:
        "1.1"  -> "00001.00001"
        "1.10" -> "00001.00010"
        "2.0"  -> "00002.00000"
        "2a"   -> "00002a"
        "10"   -> "00010"

    This ensures "1.2" sorts before "1.10" (version order, not lexicographic).
    """
    parts = code.split(".")
    padded_parts = []
    for part in parts:
        # Extract leading digits and trailing non-digits (e.g., "2a" -> "2", "a")
        match = re.match(r"^(\d+)(.*)$", part)
        if match:
            num_part = match.group(1).zfill(5)  # Zero-pad to 5 digits
            suffix = match.group(2)
            padded_parts.append(num_part + suffix)
        else:
            # No leading digits, just use as-is
            padded_parts.append(part)
    return ".".join(padded_parts)


def populate_sort_keys(apps, schema_editor):
    """Populate sort_key for all existing TrainingLesson records."""
    TrainingLesson = apps.get_model("instructors", "TrainingLesson")
    for lesson in TrainingLesson.objects.all():
        lesson.sort_key = generate_sort_key(lesson.code)
        lesson.save(update_fields=["sort_key"])


def reverse_sort_keys(apps, schema_editor):
    """Clear sort_key (reverse migration)."""
    TrainingLesson = apps.get_model("instructors", "TrainingLesson")
    TrainingLesson.objects.all().update(sort_key="")


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0003_alter_groundlessonscore_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="traininglesson",
            name="sort_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Auto-generated sort key for natural ordering (e.g., 1.2 before 1.10)",
                max_length=50,
            ),
        ),
        migrations.RunPython(populate_sort_keys, reverse_sort_keys),
        migrations.AlterModelOptions(
            name="traininglesson",
            options={"ordering": ["sort_key"]},
        ),
    ]
