# Generated by Django 5.2.15 on 2026-09-03 21:11
#
# Data Migration: Fix Legacy Score "5" → "!" (Needs Attention)
#
# Context: Legacy import (Jan 2026) failed to translate score "5" from the old system
# to the new system's "!" (Needs Attention) score. This migration corrects all 131
# orphaned score "5" records in the database by converting them to "!".
#
# Backup: Database backup completed before migration:
#   gs://m2s-database-backups-manage2soar/postgresql/m2s_all_2026-09-03_210727.sql.enc
#
# See: Issue #1001 - Training grid Max showing blank for out-of-scale scores

from django.db import migrations


def fix_legacy_score_5_to_needs_attention(apps, schema_editor):
    """Convert all legacy score '5' to '!' (Needs Attention)."""
    LessonScore = apps.get_model("instructors", "LessonScore")
    GroundLessonScore = apps.get_model("instructors", "GroundLessonScore")
    db_alias = schema_editor.connection.alias

    lesson_scores = LessonScore.objects.using(db_alias).filter(score="5")
    ground_lesson_scores = GroundLessonScore.objects.using(db_alias).filter(score="5")

    lesson_scores.update(score="!")
    ground_lesson_scores.update(score="!")

    remaining_lesson_scores = lesson_scores.count()
    remaining_ground_lesson_scores = ground_lesson_scores.count()
    if remaining_lesson_scores or remaining_ground_lesson_scores:
        raise RuntimeError(
            "Migration failed: "
            f"{remaining_lesson_scores} LessonScore and "
            f"{remaining_ground_lesson_scores} GroundLessonScore records "
            "with score '5' remain after update"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0004_add_sort_key_to_traininglesson"),
    ]

    operations = [
        migrations.RunPython(
            fix_legacy_score_5_to_needs_attention,
            migrations.RunPython.noop,
        ),
    ]
