# Generated by Django 5.2.15 on 2026-09-03 21:11
#
# Data Migration: Fix Legacy Score "5" → "!" (Needs Attention)
#
# Context: Legacy import (Jan 2026) failed to translate score "5" from the old system
# to the new system's "!" (Needs Attention) score. This migration corrects all 131
# orphaned score "5" records in the database by converting them to "!".
#
# Backup: Database backup completed before migration:
#   gs://m2s-database-backups-manage2soar/postgresql/m2s_all_2026-09-03_210727.sql.enc
#
# See: Issue #1001 - Training grid Max showing blank for out-of-scale scores

from django.db import migrations


def fix_legacy_score_5_to_needs_attention(apps, schema_editor):
    """Convert all legacy score '5' to '!' (Needs Attention)."""
    LessonScore = apps.get_model("instructors", "LessonScore")

    # Count records before migration
    count_before = LessonScore.objects.filter(score="5").count()

    if count_before > 0:
        # Update all score "5" to "!" (Needs Attention)
        updated_count, _ = LessonScore.objects.filter(score="5").update(score="!")

        # Verify the update
        count_after = LessonScore.objects.filter(score="5").count()
        if count_after != 0:
            raise RuntimeError(
                f"Migration failed: {count_after} score '5' records still exist after update"
            )

        print(
            f"\n✅ Successfully migrated {updated_count} legacy score '5' records to '!' (Needs Attention)")
    else:
        print("\n✓ No score '5' records found to migrate")


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0004_add_sort_key_to_traininglesson"),
    ]

    operations = [
        migrations.RunPython(
            fix_legacy_score_5_to_needs_attention,
            migrations.RunPython.noop,
        ),
    ]
