# Generated by Django 5.1.7 on 2025-04-12 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0005_lessonscore"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessonscore",
            name="notes",
        ),
    ]
