# Generated by Django 5.1.7 on 2025-04-13 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0007_groundinstruction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="instructionreport",
            name="simulator",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="instructionreport",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="given_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="instructionreport",
            name="report_text",
            field=models.TextField(blank=True),
        ),
    ]
