# Generated by Django 5.1.7 on 2025-04-13 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0009_alter_instructionreport_instructor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groundinstruction",
            name="lessons",
        ),
        migrations.CreateModel(
            name="GroundLessonScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.CharField(
                        choices=[
                            ("1", "Introduced (Instructor flew)"),
                            ("2", "Practiced (with instructor help)"),
                            ("3", "Solo Standard"),
                            ("4", "Checkride Standard"),
                            ("!", "Needs Attention (!)"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instructors.traininglesson",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_scores",
                        to="instructors.groundinstruction",
                    ),
                ),
            ],
            options={
                "ordering": ["lesson__code"],
                "unique_together": {("session", "lesson")},
            },
        ),
    ]
