# Generated by Django 5.2.8 on 2025-11-30 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty_roster", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dutyassignment",
            options={"ordering": ["date"]},
        ),
        migrations.AlterModelOptions(
            name="instructionslot",
            options={"ordering": ["assignment__date", "created_at"]},
        ),
        migrations.AddField(
            model_name="instructionslot",
            name="instructor_note",
            field=models.TextField(
                blank=True, help_text="Optional note from instructor to student"
            ),
        ),
        migrations.AddField(
            model_name="instructionslot",
            name="instructor_response",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                help_text="Instructor's response to the student's request",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="instructionslot",
            name="instructor_response_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the instructor responded to this request",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="instructionslot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="instructionslot",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                help_text="The instructor assigned to work with this student",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_students",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="instructionslot",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("waitlist", "Waitlist"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="instructionslot",
            unique_together={("assignment", "student")},
        ),
    ]
