# Generated by Django 5.1.7 on 2025-04-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty_roster", "0002_dutyavoidance_dutypairing_dutypreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="dutypreference",
            name="ado_percent",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dutypreference",
            name="dont_schedule",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dutypreference",
            name="duty_officer_percent",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dutypreference",
            name="instructor_percent",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dutypreference",
            name="last_duty_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dutypreference",
            name="scheduling_suspended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dutypreference",
            name="suspended_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="dutypreference",
            name="towpilot_percent",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
