# Generated by Django 5.2.8 on 2025-11-30 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("duty_roster", "0002_instruction_slot_acceptance"),
    ]

    operations = [
        # First remove constraints that reference the fields
        migrations.AlterUniqueTogether(
            name="dutyslot",
            unique_together=set(),
        ),
        # Then remove the foreign key fields
        migrations.RemoveField(
            model_name="dutyslot",
            name="duty_day",
        ),
        migrations.RemoveField(
            model_name="dutyslot",
            name="member",
        ),
        # Finally delete the models
        migrations.DeleteModel(
            name="DutySlot",
        ),
        migrations.DeleteModel(
            name="DutyDay",
        ),
    ]
