# Generated by Django 5.1.7 on 2025-04-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty_roster", "0003_dutypreference_ado_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dutypreference",
            name="max_assignments_per_month",
            field=models.PositiveIntegerField(default=2),
        ),
    ]
