# Generated by Django 5.2.9 on 2025-12-12 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty_roster", "0003_remove_dutyday_dutyslot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dutyswapoffer",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="dutyswaprequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="dutyswaprequest",
            name="is_fulfilled",
        ),
        migrations.AddField(
            model_name="dutyswapoffer",
            name="is_blackout_conflict",
            field=models.BooleanField(
                default=False,
                help_text="True if proposed swap date is in requester's blackout",
            ),
        ),
        migrations.AddField(
            model_name="dutyswapoffer",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Optional note about the offer"
            ),
        ),
        migrations.AddField(
            model_name="dutyswaprequest",
            name="accepted_offer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fulfilled_request",
                to="duty_roster.dutyswapoffer",
            ),
        ),
        migrations.AddField(
            model_name="dutyswaprequest",
            name="direct_request_to",
            field=models.ForeignKey(
                blank=True,
                help_text="If direct request, the specific member asked",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="swap_requests_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dutyswaprequest",
            name="fulfilled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dutyswaprequest",
            name="notes",
            field=models.TextField(blank=True, help_text="Reason for needing coverage"),
        ),
        migrations.AddField(
            model_name="dutyswaprequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("general", "General Broadcast"),
                    ("direct", "Direct Request"),
                ],
                default="general",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="dutyswaprequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("fulfilled", "Fulfilled"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="open",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="dutyswaprequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="dutyswapoffer",
            name="offered_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="swap_offers_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dutyswapoffer",
            name="proposed_swap_date",
            field=models.DateField(
                blank=True, help_text="Date offerer wants requester to take", null=True
            ),
        ),
        migrations.AlterField(
            model_name="dutyswapoffer",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("auto_declined", "Auto-declined"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="dutyswaprequest",
            name="is_emergency",
            field=models.BooleanField(
                default=False, help_text="Urgent request (IMSAFE, medical, etc.)"
            ),
        ),
    ]
