# Generated by Django 5.1.7 on 2025-04-22 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty_roster", "0004_dutypreference_max_assignments_per_month"),
        ("logsheet", "0031_alter_maintenanceissue_logsheet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DutyAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("is_scheduled", models.BooleanField(default=True)),
                ("is_confirmed", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "assistant_duty_officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="as_ado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "duty_officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="as_duty_officer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="as_instructor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="logsheet.airfield",
                    ),
                ),
                (
                    "surge_instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="as_surge_instructor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "surge_tow_pilot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="as_surge_tow_pilot",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tow_pilot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="as_tow_pilot",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
