# Generated by Django 5.2.9 on 2025-12-14 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty_roster", "0004_swap_request_enhancements"),
        (
            "logsheet",
            "0015_alter_glider_photo_medium_alter_glider_photo_small_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GliderReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, help_text="Date of the reserved flight"
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True,
                        help_text="Preferred start time (optional, can be general 'morning' or 'afternoon')",
                        null=True,
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, help_text="Expected end time (optional)", null=True
                    ),
                ),
                (
                    "reservation_type",
                    models.CharField(
                        choices=[
                            ("solo", "Solo Flight"),
                            ("badge", "Badge Flight"),
                            ("guest", "Guest Flying"),
                            ("other", "Other"),
                        ],
                        default="solo",
                        help_text="Type of flight operation planned",
                        max_length=20,
                    ),
                ),
                (
                    "time_preference",
                    models.CharField(
                        choices=[
                            ("morning", "Morning (first flights)"),
                            ("midday", "Midday"),
                            ("afternoon", "Afternoon"),
                            ("full_day", "Full Day"),
                            ("specific", "Specific Time"),
                        ],
                        default="morning",
                        help_text="General time preference for the reservation",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                        ],
                        db_index=True,
                        default="confirmed",
                        max_length=15,
                    ),
                ),
                (
                    "purpose",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about the planned flight (badge attempt details, guest info, etc.)",
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the reservation was cancelled",
                        null=True,
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, help_text="Reason for cancellation"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "glider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="logsheet.glider",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glider_reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date", "time_preference", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["date", "glider"], name="duty_roster_date_9d5098_idx"
                    ),
                    models.Index(
                        fields=["member", "date"], name="duty_roster_member__b74477_idx"
                    ),
                    models.Index(
                        fields=["date", "status"], name="duty_roster_date_76d8cd_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(status="confirmed"),
                        fields=("glider", "date", "time_preference"),
                        name="unique_active_reservation_per_slot",
                    )
                ],
            },
        ),
    ]
