# Generated by Django 5.2.9 on 2026-01-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty_roster", "0005_glider_reservation_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructionslot",
            name="instruction_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of instruction types requested (e.g., ['field_check', 'general'])",
            ),
        ),
        migrations.AddField(
            model_name="instructionslot",
            name="student_notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes from student about what they want to work on",
            ),
        ),
    ]
