# Generated by Django 5.1.7 on 2025-04-22 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty_roster", "0006_instructionslot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DutySwapRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("DO", "Duty Officer"),
                            ("ADO", "Assistant Duty Officer"),
                            ("INSTRUCTOR", "Instructor"),
                            ("TOW", "Tow Pilot"),
                        ],
                        max_length=20,
                    ),
                ),
                ("original_date", models.DateField()),
                ("is_emergency", models.BooleanField(default=False)),
                ("is_fulfilled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
