# Generated by Django 5.2.9 on 2026-01-26 00:42

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty_roster", "0006_add_instruction_request_details"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DutyRosterMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    tinymce.models.HTMLField(
                        blank=True,
                        default="",
                        help_text="Rich HTML message displayed at the top of the duty calendar. Leave blank to hide the announcement.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="When unchecked, the message will not be displayed even if content exists.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Last person to update this message.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duty_roster_message_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Duty Roster Message",
                "verbose_name_plural": "Duty Roster Message",
            },
        ),
    ]
