# Generated by Django 5.2.9 on 2026-01-26 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty_roster", "0007_add_duty_roster_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="dutyrostermessage",
            constraint=models.CheckConstraint(
                condition=models.Q(("id__lte", 1)),
                name="singleton_only_one_instance",
                violation_error_message="Only one Duty Roster Message instance is allowed.",
            ),
        ),
    ]
