# Generated by Django 5.2.11 on 2026-02-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty_roster", "0008_add_singleton_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opsintent",
            name="date",
            field=models.DateField(db_index=True),
        ),
    ]
