# Generated by Django 5.1.7 on 2025-04-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty_roster", "0009_opsintent"),
    ]

    operations = [
        migrations.AddField(
            model_name="dutyassignment",
            name="surge_notified",
            field=models.BooleanField(default=False),
        ),
    ]
