# Generated by Django 5.1.7 on 2025-04-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty_roster", "0010_dutyassignment_surge_notified"),
    ]

    operations = [
        migrations.AddField(
            model_name="dutyassignment",
            name="tow_surge_notified",
            field=models.BooleanField(default=False),
        ),
    ]
