# Generated by Django 5.1.7 on 2025-05-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty_roster", "0012_dutypreference_allow_weekend_double"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dutypreference",
            name="max_assignments_per_month",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "0"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                    (11, "11"),
                    (12, "12"),
                ],
                default=2,
                help_text="How many times per month you’d like to be scheduled",
            ),
        ),
    ]
