# Generated by Django 5.2.13 on 2026-04-22 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "duty_roster",
            "0012_dutyroledefinition_dutyqualificationrequirement_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DutyAssignmentRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_key", models.SlugField(max_length=64)),
                (
                    "legacy_role_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Legacy role mapping used for compatibility with fixed assignment fields.",
                        max_length=32,
                    ),
                ),
                ("shift_code", models.CharField(blank=True, default="", max_length=16)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_rows",
                        to="duty_roster.dutyassignment",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duty_assignment_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role_definition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignment_rows",
                        to="duty_roster.dutyroledefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["assignment__date", "role_key"],
                "unique_together": {("assignment", "role_key")},
            },
        ),
    ]
