# Generated by Django 5.2.13 on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty_roster", "0013_dutyassignmentrole"),
    ]

    operations = [
        migrations.AddField(
            model_name="dutyswaprequest",
            name="dynamic_role_key",
            field=models.SlugField(
                blank=True,
                default="",
                help_text="Non-legacy dynamic role key when role is DYNAMIC.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="dutyswaprequest",
            name="dynamic_role_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Display label snapshot for a dynamic role request.",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="dutyswaprequest",
            name="role",
            field=models.CharField(
                choices=[
                    ("DO", "Duty Officer"),
                    ("ADO", "Assistant Duty Officer"),
                    ("INSTRUCTOR", "Instructor"),
                    ("TOW", "Tow Pilot"),
                    ("DYNAMIC", "Dynamic Role"),
                ],
                max_length=20,
            ),
        ),
    ]
