# Generated by Django 5.2.13 on 2026-04-22 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty_roster", "0014_dutyswaprequest_dynamic_role_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="dutyswaprequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("role", "DYNAMIC"),
                        models.Q(("dynamic_role_key", ""), _negated=True),
                        models.Q(("dynamic_role_label", ""), _negated=True),
                    ),
                    models.Q(
                        models.Q(("role", "DYNAMIC"), _negated=True),
                        ("dynamic_role_key", ""),
                        ("dynamic_role_label", ""),
                    ),
                    _connector="OR",
                ),
                name="swap_request_dynamic_role_metadata_consistency",
            ),
        ),
    ]
