from django.urls import path

from . import views, views_swap

app_name = "duty_roster"

urlpatterns = [
    path("", views.roster_home, name="roster_home"),
    path("blackout/", views.blackout_manage, name="blackout_manage"),
    path("calendar/", views.duty_calendar_view, name="duty_calendar"),
    path(
        "calendar/<int:year>/<int:month>/",
        views.duty_calendar_view,
        name="duty_calendar_month",
    ),
    path(
        "calendar/day/<int:year>/<int:month>/<int:day>/",
        views.calendar_day_detail,
        name="calendar_day_detail",
    ),
    path(
        "calendar/day/<int:year>/<int:month>/<int:day>/intent/",
        views.ops_intent_toggle,
        name="ops_intent_toggle",
    ),
    path(
        "calendar/day/<int:year>/<int:month>/<int:day>/intent/form/",
        views.ops_intent_form,
        name="ops_intent_form",
    ),
    path(
        "calendar/day/<int:year>/<int:month>/<int:day>/edit/",
        views.assignment_edit_form,
        name="assignment_edit_form",
    ),
    path(
        "calendar/day/<int:year>/<int:month>/<int:day>/save/",
        views.assignment_save_form,
        name="assignment_save_form",
    ),
    path(
        "calendar/tow-signup/<int:year>/<int:month>/<int:day>/",
        views.calendar_tow_signup,
        name="calendar_tow_signup",
    ),
    path(
        "calendar/dutyofficer-signup/<int:year>/<int:month>/<int:day>/",
        views.calendar_dutyofficer_signup,
        name="calendar_dutyofficer_signup",
    ),
    path(
        "calendar/instructor-signup/<int:year>/<int:month>/<int:day>/",
        views.calendar_instructor_signup,
        name="calendar_instructor_signup",
    ),
    path(
        "calendar/ado-signup/<int:year>/<int:month>/<int:day>/",
        views.calendar_ado_signup,
        name="calendar_ado_signup",
    ),
    path(
        "calendar/ad-hoc/<int:year>/<int:month>/<int:day>/",
        views.calendar_ad_hoc_start,
        name="calendar_ad_hoc_start",
    ),
    path(
        "calendar/ad-hoc/confirm/<int:year>/<int:month>/<int:day>/",
        views.calendar_ad_hoc_confirm,
        name="calendar_ad_hoc_confirm",
    ),
    path(
        "calendar/ad-hoc/cancel/<int:year>/<int:month>/<int:day>/",
        views.calendar_cancel_ops_modal,
        name="calendar_cancel_ops_modal",
    ),
    path(
        "calendar/ad-hoc/cancel/confirm/<int:year>/<int:month>/<int:day>/",
        views.calendar_cancel_ops_day,
        name="calendar_cancel_ops_day",
    ),
    path("propose-roster/", views.propose_roster, name="propose_roster"),
    path(
        "duty-delinquents/detail/",
        views.duty_delinquents_detail,
        name="duty_delinquents_detail",
    ),
    # Instruction Request URLs
    path(
        "instruction/request/<int:year>/<int:month>/<int:day>/",
        views.request_instruction,
        name="request_instruction",
    ),
    path(
        "instruction/cancel/<int:slot_id>/",
        views.cancel_instruction_request,
        name="cancel_instruction_request",
    ),
    path(
        "instruction/my-requests/",
        views.my_instruction_requests,
        name="my_instruction_requests",
    ),
    # Instructor Management URLs
    path(
        "instruction/instructor-requests/",
        views.instructor_requests,
        name="instructor_requests",
    ),
    path(
        "instruction/respond/<int:slot_id>/",
        views.instructor_respond,
        name="instructor_respond",
    ),
    # Duty Swap URLs
    path(
        "swap/request/create/<int:year>/<int:month>/<int:day>/<str:role>/",
        views_swap.create_swap_request,
        name="create_swap_request",
    ),
    path(
        "swap/my-requests/",
        views_swap.my_swap_requests,
        name="my_swap_requests",
    ),
    path(
        "swap/open-requests/",
        views_swap.open_swap_requests,
        name="open_swap_requests",
    ),
    path(
        "swap/request/<int:request_id>/",
        views_swap.swap_request_detail,
        name="swap_request_detail",
    ),
    path(
        "swap/request/<int:request_id>/cancel/",
        views_swap.cancel_swap_request,
        name="cancel_swap_request",
    ),
    path(
        "swap/request/<int:request_id>/convert/",
        views_swap.convert_to_general,
        name="convert_to_general",
    ),
    path(
        "swap/request/<int:request_id>/offer/",
        views_swap.make_offer,
        name="make_swap_offer",
    ),
    path(
        "swap/request/<int:request_id>/decline/",
        views_swap.decline_swap_request,
        name="decline_swap_request",
    ),
    path(
        "swap/offer/<int:offer_id>/accept/",
        views_swap.accept_offer,
        name="accept_swap_offer",
    ),
    path(
        "swap/offer/<int:offer_id>/decline/",
        views_swap.decline_offer,
        name="decline_swap_offer",
    ),
    path(
        "swap/offer/<int:offer_id>/withdraw/",
        views_swap.withdraw_offer,
        name="withdraw_swap_offer",
    ),
]
