# Generated by Django 5.2.6 on 2025-10-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CronJobLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_name",
                    models.CharField(
                        help_text="Unique identifier for the scheduled job",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "locked_by",
                    models.CharField(
                        help_text="Pod identifier (hostname + process ID)",
                        max_length=100,
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the lock was acquired"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When the lock expires (safety mechanism for crashed pods)"
                    ),
                ),
            ],
            options={
                "verbose_name": "CronJob Lock",
                "verbose_name_plural": "CronJob Locks",
                "db_table": "cronjob_locks",
                "indexes": [
                    models.Index(
                        fields=["job_name"], name="cronjob_loc_job_nam_0ccec5_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="cronjob_loc_expires_5e9f42_idx"
                    ),
                ],
            },
        ),
    ]
