# Generated by Django 5.2.9 on 2025-12-12 03:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cronjoblock",
            name="locked_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When the lock was acquired",
            ),
        ),
    ]
