# Generated by Django 5.2.6 on 2025-09-24 22:06

import utils.upload_entropy
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=200)),
                ('domain_name', models.CharField(help_text='Primary domain name (e.g. example.org)', max_length=200)),
                ('club_abbreviation', models.CharField(help_text='Short abbreviation (e.g. SSS)', max_length=20)),
                ('club_logo', models.ImageField(blank=True, null=True, upload_to=utils.upload_entropy.upload_site_logo)),
                ('club_nickname', models.CharField(blank=True, help_text='Nickname or short name (e.g. Skyline)', max_length=40)),
                ('extra_config', models.JSONField(blank=True, help_text='Other club-specific settings (dict)', null=True)),
            ],
        ),
    ]
