# Generated by Django 5.2.6 on 2025-09-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='allow_glider_reservations',
            field=models.BooleanField(default=False, help_text='We allow members to reserve club gliders ahead of time.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='allow_two_seater_reservations',
            field=models.BooleanField(default=False, help_text='We allow members to reserve club two seaters ahead of time.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='assistant_duty_officer_title',
            field=models.CharField(default='Assistant Duty Officer', help_text='We refer to the position of Assistant Duty Officer as ...', max_length=40),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='duty_officer_title',
            field=models.CharField(default='Duty Officer', help_text='We refer to the position of Duty Officer as ...', max_length=40),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='equipment_manager_title',
            field=models.CharField(default='Equipment Manager', help_text='We refer to the person who manages the equipment as ...', max_length=40),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='membership_manager_title',
            field=models.CharField(default='Membership Manager', help_text='We refer to the person who manages the membership as ...', max_length=40),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='schedule_assistant_duty_officers',
            field=models.BooleanField(default=False, help_text='We schedule Assistant Duty Officers ahead of time'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='schedule_duty_officers',
            field=models.BooleanField(default=False, help_text='We schedule Duty Officers ahead of time'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='schedule_instructors',
            field=models.BooleanField(default=False, help_text='We schedule Instructors ahead of time'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='schedule_tow_pilots',
            field=models.BooleanField(default=False, help_text='We schedule tow pilots ahead of time'),
        ),
    ]
