# Generated by automated patch
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0004_remove_siteconfiguration_am_towpilot_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="redaction_notification_dedupe_minutes",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Dedupe window (minutes) for member redaction notifications.",
            ),
        )
    ]
