# Generated by Django 5.2.6 on 2025-10-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0005_add_redaction_notification_dedupe_minutes"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The display name for this membership status (e.g., 'Full Member')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether members with this status are considered 'active' and can access member features",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Sort order for display in dropdowns and lists (lower numbers appear first)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of what this membership status means",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Membership Status",
                "verbose_name_plural": "Membership Statuses",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
