# Generated by Django 5.2.6 on 2025-10-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0007_auto_20251028_1903"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="club_address_line1",
            field=models.CharField(
                blank=True, help_text="Street address line 1", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="club_address_line2",
            field=models.CharField(
                blank=True, help_text="Street address line 2 (optional)", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="club_city",
            field=models.CharField(blank=True, help_text="City", max_length=50),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="club_country",
            field=models.CharField(
                blank=True, default="USA", help_text="Country", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="club_phone",
            field=models.CharField(
                blank=True, help_text="Main club phone number (optional)", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="club_state",
            field=models.CharField(
                blank=True, help_text="State/Province", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="club_zip_code",
            field=models.CharField(
                blank=True, help_text="ZIP/Postal code", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="contact_response_info",
            field=models.TextField(
                blank=True,
                default="Our member managers will receive your message immediately\nWe typically respond within 24-48 hours\nFor urgent questions, feel free to visit us at the airfield during operations\nAll contact information is kept private and not shared with third parties",
                help_text="Information about what happens after contact form submission (one item per line)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="contact_welcome_text",
            field=models.TextField(
                blank=True,
                default="Interested in learning to fly gliders? Have questions about our club? We'd love to hear from you! Fill out the form below and one of our member managers will get back to you soon.",
                help_text="Welcome text displayed on the contact form page",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="operations_info",
            field=models.TextField(
                blank=True,
                default="We typically fly on weekends and some weekdays when weather permits. Check our calendar or contact us for current schedule information.",
                help_text="Information about club operations schedule",
            ),
        ),
    ]
