# Generated by Django 5.2.6 on 2025-11-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0008_siteconfiguration_club_address_line1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="operations_end_period",
            field=models.CharField(
                blank=True,
                default="Last weekend of October",
                help_text="When club operations typically end each year (e.g., 'Last weekend of October', 'Second weekend of December')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="operations_start_period",
            field=models.CharField(
                blank=True,
                default="First weekend of May",
                help_text="When club operations typically start each year (e.g., 'First weekend of May', 'Second weekend of April')",
                max_length=100,
            ),
        ),
    ]
