# Generated by Django 5.2.8 on 2025-11-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0009_siteconfiguration_operations_end_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="visiting_pilot_auto_approve",
            field=models.BooleanField(
                default=True,
                help_text="Automatically approve visiting pilots (they can fly immediately after signup)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="visiting_pilot_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable quick signup for visiting pilots via QR code",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="visiting_pilot_require_rating",
            field=models.BooleanField(
                default=True,
                help_text="Require glider rating for visiting pilot signup",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="visiting_pilot_require_ssa",
            field=models.BooleanField(
                default=True,
                help_text="Require SSA membership number for visiting pilot signup",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="visiting_pilot_status",
            field=models.CharField(
                default="Affiliate Member",
                help_text="Membership status assigned to visiting pilots after quick signup",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="visiting_pilot_welcome_text",
            field=models.TextField(
                blank=True,
                default="Welcome, visiting pilot! Complete this quick form to get added to our system so you can fly with us today.",
                help_text="Welcome message displayed on visiting pilot signup page",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="operations_end_period",
            field=models.CharField(
                blank=True,
                default="Last weekend of October",
                help_text="When club operations typically end each year. Examples: 'Last weekend of October', '2nd weekend of Dec', 'Third weekend in November'. Leave both fields blank to include all dates year-round.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="operations_start_period",
            field=models.CharField(
                blank=True,
                default="First weekend of May",
                help_text="When club operations typically start each year. Examples: 'First weekend of May', '1st weekend of Apr', 'Second weekend in March', 'Last weekend Oct'. Supports: first/1st, second/2nd, third/3rd, fourth/4th, last + full month names or abbreviations (Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec)",
                max_length=100,
            ),
        ),
    ]
