# Generated by Django 5.2.8 on 2025-11-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0010_add_visiting_pilot_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="visiting_pilot_token",
            field=models.CharField(
                blank=True,
                help_text="Security token for visiting pilot signup URLs (regenerated automatically)",
                max_length=20,
            ),
        ),
    ]
