# Generated by Django 5.2.8 on 2025-11-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0011_add_visiting_pilot_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="visiting_pilot_token_created",
            field=models.DateTimeField(
                blank=True,
                help_text="When the current visiting pilot token was created",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="visiting_pilot_token",
            field=models.CharField(
                blank=True,
                help_text="Security token for visiting pilot signup URLs (generated on-demand, expires when logsheet finalized)",
                max_length=20,
            ),
        ),
    ]
