# Generated by Django 5.2.8 on 2025-11-17 14:28

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0012_add_token_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="membership_application_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable membership applications for non-logged-in users",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="membership_application_fees_text",
            field=models.TextField(
                blank=True,
                help_text="Information about membership fees and costs (displayed on application form)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="membership_application_terms",
            field=tinymce.models.HTMLField(
                blank=True,
                default="",
                help_text="Club rules and terms that applicants must agree to (HTML allowed)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="membership_application_welcome_text",
            field=models.TextField(
                blank=True,
                default="Thank you for your interest in joining our soaring club! Please fill out this membership application. Our membership managers will review your application and contact you soon.",
                help_text="Welcome text displayed on the membership application form",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="membership_auto_approve",
            field=models.BooleanField(
                default=False,
                help_text="Automatically approve membership applications (bypass manual review)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="membership_require_references",
            field=models.BooleanField(
                default=True,
                help_text="Require references as part of the membership application",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="membership_waiting_list_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable waiting list for membership applications when at capacity",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="new_member_status",
            field=models.CharField(
                default="Probationary Member",
                help_text="Membership status assigned to newly approved members",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="visiting_pilot_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable quick signup for visiting pilots via QR code",
            ),
        ),
    ]
