# Generated by Django 5.2.8 on 2025-11-17 14:35

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0013_add_membership_application_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="membership_application_fees_text",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="membership_application_welcome_text",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="membership_require_references",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="membership_waiting_list_enabled",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="new_member_status",
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="membership_application_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable the membership application form for new members",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="membership_application_terms",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Terms and conditions text shown on membership application form",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="membership_auto_approve",
            field=models.BooleanField(
                default=False,
                help_text="Automatically approve new membership applications (bypass manual review)",
            ),
        ),
    ]
