# Generated by Django 5.2.8 on 2025-11-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0014_add_membership_application_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="allow_towplane_rental",
            field=models.BooleanField(
                default=False,
                help_text="We allow towplanes to be rented for non-towing purposes (sightseeing flights, flight reviews, aircraft retrieval, etc.).",
            ),
        ),
    ]
