# Generated by Django 5.2.9 on 2025-12-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0016_add_role_account_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique identifier for this list (e.g., 'instructors', 'board')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        blank=True,
                        help_text="Full email address for this list (e.g., instructors@example.org). Optional - for documentation only.",
                        max_length=254,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of this mailing list's purpose",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive lists are not included in API responses",
                    ),
                ),
                (
                    "criteria",
                    models.JSONField(
                        default=list,
                        help_text="List of criteria codes that determine membership (OR logic)",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Sort order for display in admin (lower numbers first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mailing List",
                "verbose_name_plural": "Mailing Lists",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
