# Generated by Django 5.2.9 on 2025-12-06 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0017_add_mailing_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailinglist",
            name="email_address",
        ),
    ]
