# Generated by Django 5.2.9 on 2025-12-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0018_remove_mailinglist_email_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="instruction_surge_threshold",
            field=models.PositiveIntegerField(
                default=4,
                help_text="Number of instruction requests that triggers surge alerts (default: 4)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="tow_surge_threshold",
            field=models.PositiveIntegerField(
                default=6,
                help_text="Number of tow requests that triggers 'high demand' surge alerts (default: 6)",
            ),
        ),
    ]
