# Generated by Django 5.2.9 on 2025-12-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0019_surge_thresholds"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="duty_roster_announcement",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional announcement from the Roster Manager displayed on the duty calendar. Visible to all members.",
            ),
        ),
    ]
