# Generated by Django 5.2.9 on 2025-12-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0020_add_duty_roster_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="max_reservations_per_year",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Maximum number of glider reservations a member can make per calendar year (default: 3). Set to 0 for unlimited.",
            ),
        ),
    ]
