# Generated by Django 5.2.9 on 2025-12-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0021_glider_reservation_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="max_reservations_per_month",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Maximum number of glider reservations a member can make per calendar month. Set to 0 for unlimited (default: 0).",
            ),
        ),
    ]
