# Generated by Django 5.2.9 on 2025-12-16 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0022_add_max_reservations_per_month"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChargeableItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the item (e.g., 'T-Shirt Large', 'Aerotow Retrieve')",
                        max_length=100,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Unit price in dollars",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("each", "Each"), ("hour", "Per Hour")],
                        default="each",
                        help_text="Pricing unit - 'Each' for items, 'Per Hour' for time-based charges like retrieve tach time",
                        max_length=10,
                    ),
                ),
                (
                    "allows_decimal_quantity",
                    models.BooleanField(
                        default=False,
                        help_text="Allow decimal quantities (e.g., 1.8 hours for tach time). Leave unchecked for whole-number items like t-shirts.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive items won't appear in the charge dropdown",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description or notes about this item",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Sort order for display (lower numbers appear first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Chargeable Item",
                "verbose_name_plural": "Chargeable Items",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="waive_rental_fee_on_retrieve",
            field=models.BooleanField(
                default=False,
                help_text="Don't charge for glider rental on retrieve flights (some clubs don't charge rental for the ferry flight back).",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="waive_tow_fee_on_retrieve",
            field=models.BooleanField(
                default=False,
                help_text="Don't charge for the aerotow on retrieve flights (some clubs waive the tow fee when retrieving a landed-out glider).",
            ),
        ),
    ]
