# Generated by Django 5.2.9 on 2026-01-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0023_add_chargeable_items_and_retrieve_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="quick_altitude_buttons",
            field=models.CharField(
                default="2000,3000",
                help_text="Comma-separated list of altitude values (in feet) for quick-select buttons on flight forms. Example: 300,1000,1500,2000,3000",
                max_length=100,
            ),
        ),
    ]
