# Generated by Django 5.2.9 on 2026-01-11 00:31

from django.db import migrations


def update_altitude_buttons(apps, schema_editor):
    """Update existing SiteConfiguration records with new default altitude buttons."""
    SiteConfiguration = apps.get_model("siteconfig", "SiteConfiguration")
    # Only update records that still have the old default value
    SiteConfiguration.objects.filter(quick_altitude_buttons="2000,3000").update(
        quick_altitude_buttons="300,1000,1500,2000,3000"
    )


def reverse_altitude_buttons(apps, schema_editor):
    """Reverse migration - restore old default."""
    SiteConfiguration = apps.get_model("siteconfig", "SiteConfiguration")
    SiteConfiguration.objects.filter(
        quick_altitude_buttons="300,1000,1500,2000,3000"
    ).update(quick_altitude_buttons="2000,3000")


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0024_add_quick_altitude_buttons"),
    ]

    operations = [
        migrations.RunPython(update_altitude_buttons, reverse_altitude_buttons),
    ]
