# Generated by Django 5.2.9 on 2026-01-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0025_update_quick_altitude_buttons_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailinglist",
            name="bypass_whitelist",
            field=models.BooleanField(
                default=False,
                help_text="Allow this list to receive mail from ANYONE, not just whitelisted senders (still requires SPF PASS). Use for service accounts like treasurer@ or webmaster@ that need to receive verification emails from external services.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="manual_whitelist",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Email addresses allowed to send to mailing lists (one per line). Use for trusted non-members like former members, vendors, or partners.",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="quick_altitude_buttons",
            field=models.CharField(
                default="300,1000,1500,2000,3000",
                help_text="Comma-separated list of altitude values (in feet) for quick-select buttons on flight forms. Example: 300,1000,1500,2000,3000",
                max_length=100,
            ),
        ),
    ]
