# Generated by Django 5.2.11 on 2026-02-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0026_add_whitelist_bypass_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="canonical_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Canonical URL for all outbound email links (e.g., https://www.skylinesoaring.org). This ensures consistent URLs in emails regardless of which domain users access. Do NOT include trailing slash. Leave blank to use SITE_URL environment variable.",
                max_length=255,
                verbose_name="Canonical Email URL",
            ),
            preserve_default=False,
        ),
    ]
