# Generated by Django 5.2.11 on 2026-02-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0027_add_canonical_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="duty_roster_announcement",
            field=models.TextField(
                blank=True,
                default="",
                help_text="DEPRECATED: Use the new Duty Roster Message editor at /duty_roster/message/edit/ instead. This field will be removed in a future release.",
            ),
        ),
    ]
