# Generated by Django 5.2.11 on 2026-02-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0028_alter_siteconfiguration_duty_roster_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="use_ortools_scheduler",
            field=models.BooleanField(
                default=False,
                help_text="Use OR-Tools constraint programming scheduler instead of legacy weighted-random algorithm. OR-Tools provides globally optimal solutions, deterministic output, and better constraint handling. Disable this flag to instantly roll back to legacy scheduler if needed.",
                verbose_name="Use OR-Tools Scheduler",
            ),
        ),
    ]
