# Generated by Django 5.2.11 on 2026-02-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0029_add_use_ortools_scheduler_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="instructors_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Email address to notify when a surge instructor is needed (e.g. your instructors mailing list address). When a duty instructor accumulates 3 or more accepted students, this address receives an alert asking for a volunteer surge instructor. Leave blank to suppress the alert.",
                max_length=254,
            ),
        ),
    ]
