# Generated by Django 5.2.11 on 2026-02-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0030_add_instructors_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="instruction_request_max_days_ahead",
            field=models.PositiveIntegerField(
                default=14,
                help_text="How many days in advance a student may request instruction. Only applies when 'Restrict instruction request window' is enabled. Default: 14 (2 weeks).",
                verbose_name="Max days ahead for instruction requests",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="restrict_instruction_requests_window",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, students may only request instruction within a configured number of days before the scheduled date. Disable to allow requests at any time in advance.",
                verbose_name="Restrict instruction request window",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="instructors_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Email address to notify when a surge instructor is needed (e.g. your instructors mailing list address). When a duty instructor has accepted at least the configured instruction surge threshold of students, and no surge instructor is already assigned and no prior alert has been sent for that assignment, this address receives a request for a volunteer surge instructor. Leave blank to suppress the alert.",
                max_length=254,
            ),
        ),
    ]
