# Generated by Django 5.2.11 on 2026-02-20
# Separated from 0031 so each migration addresses a single concern.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0031_restrict_instruction_request_window"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="instructors_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text=(
                    "Email address to notify when a surge instructor is needed "
                    "(e.g. your instructors mailing list address). When a duty instructor "
                    "has accepted at least the configured instruction surge threshold of "
                    "students, and no surge instructor is already assigned and no prior alert "
                    "has been sent for that assignment, this address receives a request for a "
                    "volunteer surge instructor. Leave blank to suppress the alert."
                ),
                max_length=254,
            ),
        ),
    ]
