# Generated by Django 5.2.11 on 2026-02-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0033_enable_instruction_window_for_existing_rows"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="webcam_snapshot_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Full URL used server-side to fetch a single JPEG snapshot from the webcam. May include credentials in the URL (e.g. http://host:9137/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=USER&pwd=PASS). ⚠️ This value is NEVER sent to the browser — the Django server fetches it and proxies the image bytes. Leave blank to disable the webcam feature entirely.",
                max_length=500,
                verbose_name="Webcam snapshot URL",
            ),
        ),
    ]
