# Generated by Django 5.2.11 on 2026-03-30

from django.db import migrations, models
from django.db.models import F


def copy_existing_instruction_thresholds(apps, schema_editor):
    SiteConfiguration = apps.get_model("siteconfig", "SiteConfiguration")
    SiteConfiguration.objects.all().update(
        instruction_max_students_per_instructor=F("instruction_surge_threshold")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0034_webcam_snapshot_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="instruction_max_students_per_instructor",
            field=models.PositiveIntegerField(
                default=4,
                help_text="Maximum accepted students per instructor for a duty day (default: 4). This is separate from the instruction surge threshold, which only controls when surge help notifications are triggered.",
            ),
        ),
        migrations.RunPython(
            copy_existing_instruction_thresholds,
            migrations.RunPython.noop,
        ),
    ]
