# Generated by Django 5.2.11 on 2026-04-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0035_add_instruction_max_students_per_instructor"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="reservation_limit_period",
            field=models.CharField(
                choices=[("yearly", "Yearly"), ("quarterly", "Quarterly")],
                default="yearly",
                help_text="Primary reservation limit period. Set to yearly or quarterly. Existing clubs default to yearly.",
                max_length=20,
            ),
        ),
    ]
