# Generated by Django 5.2.12 on 2026-04-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0036_add_reservation_limit_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="max_reservations_per_year",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Maximum number of glider reservations a member can make per primary reservation limit period (default: 3). Set to 0 for unlimited.",
            ),
        ),
    ]
