# Generated by Django 5.2.12 on 2026-04-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0040_merge_0037_0039"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="commercial_pilot_title",
            field=models.CharField(
                default="Commercial Pilot",
                help_text="We refer to the position of Commercial Pilot as ...",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="commercial_rides_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable commercial ride ticketing and logsheet workflows",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="schedule_commercial_pilots",
            field=models.BooleanField(
                default=False, help_text="We schedule Commercial Pilots ahead of time"
            ),
        ),
    ]
