# Generated by Django 5.2.11 on 2026-05-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0042_siteconfiguration_enable_dynamic_duty_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="secretary_title",
            field=models.CharField(
                default="Secretary",
                help_text="We refer to the position of Secretary as ...",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="treasurer_title",
            field=models.CharField(
                default="Treasurer",
                help_text="We refer to the position of Treasurer as ...",
                max_length=40,
            ),
        ),
    ]
