# Generated by Django 5.2.14 on 2026-05-29 15:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0043_siteconfiguration_secretary_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="billing_rules_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable membership-status billing rules for tow discounts and instructor charge multipliers. When disabled, base pricing applies.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="default_instructor_rate_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="Fallback instructor charge multiplier when instructor-time charges are enabled and no membership-status-specific rule exists.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("10.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="default_tow_discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Fallback tow discount percentage when billing rules are enabled and no membership-status-specific rule exists. Positive values are discounts; negative values are surcharges.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("-100.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="instructor_time_charges_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable instructor-time billing workflows that can use membership-status rate multipliers.",
            ),
        ),
        migrations.CreateModel(
            name="MembershipBillingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tow_discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Tow discount percentage for this membership status. Positive values are discounts; negative values are surcharges.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("-100.00")
                            ),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "instructor_rate_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Instructor-time charge multiplier for this membership status (for example, 0.80 = 20% discount).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("10.00")),
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive rules are ignored during billing calculations.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "membership_status",
                    models.OneToOneField(
                        help_text="Membership status this billing rule applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_rule",
                        to="siteconfig.membershipstatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membership Billing Rule",
                "verbose_name_plural": "Membership Billing Rules",
                "ordering": [
                    "membership_status__sort_order",
                    "membership_status__name",
                ],
            },
        ),
    ]
