# Generated by Django 5.2.14 on 2026-05-29 16:00

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0044_siteconfiguration_billing_rules_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipbillingrule",
            name="charge_instruction_per_instructed_flight",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, applies the flat instruction fee to flights where an instructor is recorded.",
            ),
        ),
        migrations.AddField(
            model_name="membershipbillingrule",
            name="glider_rental_rate_per_hour_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional absolute glider rental hourly rate override used in matrix mode.",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="membershipbillingrule",
            name="instruction_flat_fee_per_flight",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Flat instruction fee per flight used in matrix mode when instruction charging is enabled for this status.",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="membershipbillingrule",
            name="tow_hookup_fee_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional absolute tow hookup fee override used in matrix mode. Leave blank to use the towplane scheme hookup fee.",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="membershipbillingrule",
            name="tow_rate_per_1000ft_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional absolute tow altitude rate override used in matrix mode. Calculated as ceil(altitude/1000) * rate.",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="billing_pricing_mode",
            field=models.CharField(
                choices=[("discount", "Discount Mode"), ("matrix", "Matrix Mode")],
                default="discount",
                help_text="Discount mode applies percentage modifiers. Matrix mode applies absolute per-status component overrides for tow/rental/instruction.",
                max_length=20,
            ),
        ),
    ]
