# Generated by Django 5.2.14 on 2026-05-29 17:29

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0022_flight_instruction_fee_actual"),
        (
            "siteconfig",
            "0045_membershipbillingrule_charge_instruction_per_instructed_flight_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="minimum_billable_rental_minutes",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Minimum billable glider rental duration in minutes. Set to 0 to disable minimum billing floor.",
            ),
        ),
        migrations.CreateModel(
            name="MembershipGliderRentalRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hourly_rate_override",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Absolute hourly rental rate for this membership status + glider.",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive rules are ignored during rental calculations.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "glider",
                    models.ForeignKey(
                        help_text="Glider this rental override applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_rental_rules",
                        to="logsheet.glider",
                    ),
                ),
                (
                    "membership_status",
                    models.ForeignKey(
                        help_text="Membership status this glider-specific rental override applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glider_rental_rules",
                        to="siteconfig.membershipstatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membership Glider Rental Rule",
                "verbose_name_plural": "Membership Glider Rental Rules",
                "ordering": [
                    "membership_status__sort_order",
                    "membership_status__name",
                    "glider__n_number",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("membership_status", "glider"),
                        name="uniq_membership_status_glider_rental_rule",
                    )
                ],
            },
        ),
    ]
