# Generated by Django 5.2.14 on 2026-06-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "siteconfig",
            "0046_siteconfiguration_minimum_billable_rental_minutes_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="club_timezone",
            field=models.CharField(
                default="UTC",
                help_text="IANA timezone for club-local operational dates/times (for example, America/New_York).",
                max_length=64,
            ),
        ),
    ]
