# Generated by Django 5.2.14 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0047_siteconfiguration_club_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="billing_app_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable the member billing ledger, billing views, and automatic ledger posting for this site. Billing rule settings only apply when this master switch is enabled.",
            ),
        ),
    ]
