# Generated by Django 5.2.15 on 2026-08-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0050_siteconfiguration_billing_period_close_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="visiting_pilot_max_visits_per_year",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Maximum number of times a person may check in as a visiting pilot per calendar year. Set to 0 for unlimited.",
            ),
        ),
    ]
