# Generated by Django 5.2.14 on 2026-08-25 20:47

import siteconfig.models
from django.db import migrations, models


def default_member_profile_field_policies():
    return {
        "username": "disabled",
        "email": "disabled",
        "phone": "request",
        "address": "request",
        "emergency_contacts": "request",
        "nickname": "request",
        "profile_photo": "direct",
        "biography": "direct",
        "password": "direct",
        "contact_visibility": "direct",
    }


def set_existing_profile_field_policies(apps, schema_editor):
    SiteConfiguration = apps.get_model("siteconfig", "SiteConfiguration")
    SiteConfiguration.objects.all().update(
        member_profile_field_policies=default_member_profile_field_policies()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0051_siteconfiguration_visiting_pilot_max_visits_per_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='member_profile_field_policies',
            field=models.JSONField(default=siteconfig.models.default_member_profile_field_policies, help_text='Per-field member profile policies.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='member_profile_self_service_enabled',
            field=models.BooleanField(default=True, help_text='Allow members to update or request changes to configured profile fields.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='share_member_address_by_default',
            field=models.BooleanField(default=True, help_text='Share member addresses by default unless a member changes it.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='share_member_email_by_default',
            field=models.BooleanField(default=True, help_text='Share member email addresses by default unless a member changes it.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='share_member_phone_by_default',
            field=models.BooleanField(default=True, help_text='Share member phone numbers by default unless a member changes it.'),
        ),
        migrations.RunPython(
            set_existing_profile_field_policies, migrations.RunPython.noop
        ),
    ]
