# Generated by Django 5.2.14 on 2026-08-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0051_siteconfiguration_visiting_pilot_max_visits_per_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="share_member_address_by_default",
            field=models.BooleanField(
                default=True,
                help_text="Share member addresses by default unless a member changes it.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="share_member_email_by_default",
            field=models.BooleanField(
                default=True,
                help_text="Share member email addresses by default unless a member changes it.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="share_member_phone_by_default",
            field=models.BooleanField(
                default=True,
                help_text="Share member phone numbers by default unless a member changes it.",
            ),
        ),
    ]
