#############################################################
#
# Django settings for Manage2Soar project.
#
# Generated by 'django-admin startproject' using Django 5.2.
#
# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.2/ref/settings/
#
#############################################################


import logging
import os
import re
import sys
from pathlib import Path

from django.contrib.messages import constants as messages
from django.shortcuts import redirect
from dotenv import load_dotenv
from google.oauth2 import service_account

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Define the base directory of the Django project.
# This calculates the path to the directory containing 'manage.py'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Detect if we're running in a test environment to prevent test pollution
TESTING = any(arg.startswith("test") for arg in sys.argv[1:2])

# Load environment variables from the .env file located in the BASE_DIR.
# This ensures that sensitive information and configuration can be managed
# outside of the codebase, improving security and flexibility.
dotenv_path = BASE_DIR / ".env"
if dotenv_path.exists():
    load_dotenv(dotenv_path)
elif not TESTING:  # Only log if not in test environment
    logger = logging.getLogger(__name__)
    logger.warning(
        f".env file not found at {dotenv_path}. Relying on system environment variables."
    )

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

if not SECRET_KEY:
    raise ValueError("DJANGO_SECRET_KEY not set in environment!")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() in ("true", "1", "yes")
STATIC_ROOT = BASE_DIR / "staticfiles"

# Application definition

INSTALLED_APPS = [
    "import_export",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "social_django",
    "tinymce",
    "members",
    "logsheet",
    "duty_roster",
    "analytics",
    "cms",
    "django.contrib.humanize",
    "reversion",
    "django_htmx",
    "django_extensions",
    "instructors.apps.InstructorsConfig",
    "knowledgetest.apps.KnowledgetestConfig",
    "siteconfig",
    "storages",
    "notifications",
    "utils",
    "widget_tweaks",
]


LOGIN_URL = "/members/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"
AUTH_USER_MODEL = "members.Member"

MIDDLEWARE = [
    "utils.middleware.HealthCheckMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "utils.middleware.KioskAutoLoginMiddleware",  # Issue #364: Kiosk auto-reauth
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
]

LOGIN_REQUIRED_MIDDLEWARE = ("django.contrib.auth.middleware.AuthenticationMiddleware",)


def login_required_middleware(get_response):
    def middleware(request):
        if not request.user.is_authenticated and not request.path.startswith(
            "/accounts/login/"
        ):
            return redirect("login")
        return get_response(request)

    return middleware


ROOT_URLCONF = "manage2soar.urls"
DEFAULT_AIRFIELD_ID = 1

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "social_django.context_processors.backends",
                "social_django.context_processors.login_redirect",
                "django.template.context_processors.static",
                "django.template.context_processors.media",
            ],
        },
    },
]

WSGI_APPLICATION = "manage2soar.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "OPTIONS": {
            "sslmode": os.getenv("DB_SSLMODE", "require"),
        },
    },
    "legacy": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("LEGACY_DB_NAME"),
        "USER": os.getenv("LEGACY_DB_USER"),
        "PASSWORD": os.getenv("LEGACY_DB_PASSWORD"),
        "HOST": os.getenv("LEGACY_DB_HOST", "localhost"),
        "PORT": os.getenv("LEGACY_DB_PORT", "5555"),
    },
}


# These are to allow us to have users log in with Google OAuth2
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv("SOCIAL_AUTH_GOOGLE_OAUTH2_KEY")
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv("SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET")

SOCIAL_AUTH_PIPELINE = (
    # Standard steps
    # Get user details from provider
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",  # Get provider UID
    # Check if auth is allowed
    "social_core.pipeline.social_auth.auth_allowed",
    # Try to find existing social user
    "social_core.pipeline.social_auth.social_user",
    # 🔁 NEW: Associate by email if not linked yet (password-first → OAuth2)
    "social_core.pipeline.social_auth.associate_by_email",
    # 🛠️ Custom steps — insert after association
    "members.pipeline.debug_pipeline_data",  # Log details
    # 🚫 Issue #164: Redirect unknown users to membership application
    "members.pipeline.redirect_unknown_users_to_application",
    # Create proper username format (only for existing users)
    "members.pipeline.create_username",
    # Default username getter
    "social_core.pipeline.user.get_username",
    # 🚫 REMOVED: No longer create users automatically
    # "social_core.pipeline.user.create_user",  # Issue #164
    "members.pipeline.set_default_membership_status",  # Set membership status
    # Fetch profile picture from Google
    "members.pipeline.fetch_google_profile_picture",
    # Standard steps to finalize
    "social_core.pipeline.social_auth.associate_user",  # Link social to user
    "social_core.pipeline.social_auth.load_extra_data",  # Load extras
    "social_core.pipeline.user.user_details",  # Update user fields
)

# Issue #462: Protect member names from being overwritten by Google OAuth data.
# The user_details pipeline step would otherwise update first_name/last_name
# from the Google account on every login. These fields should remain independent
# and editable only by the member or admin.
SOCIAL_AUTH_PROTECTED_USER_FIELDS = ["first_name", "last_name"]


MESSAGE_TAGS = {
    messages.ERROR: "danger",  # maps Django "error" to Bootstrap "danger"
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

#############################################################
# ---- Google Cloud Storage (GCS) / django-storages config ----
# All GCS-related settings consolidated here for clarity
# GCS is optional - if GS_BUCKET_NAME is not set, use local storage
#############################################################
GS_BUCKET_NAME = os.getenv("GS_BUCKET_NAME")

# Multi-tenant support: Club-specific storage paths
CLUB_PREFIX = os.getenv("CLUB_PREFIX", "ssc")  # Default to Skyline Soaring Club

# Validate CLUB_PREFIX to prevent path traversal attacks
if not re.match(r"^[a-zA-Z0-9-]+$", CLUB_PREFIX):
    raise Exception(
        f"Invalid CLUB_PREFIX '{CLUB_PREFIX}'. "
        "CLUB_PREFIX must contain only alphanumeric characters and hyphens. "
        "This prevents path traversal security issues."
    )

GS_MEDIA_LOCATION = os.getenv("GS_MEDIA_LOCATION", f"{CLUB_PREFIX}/media")
GS_STATIC_LOCATION = os.getenv("GS_STATIC_LOCATION", f"{CLUB_PREFIX}/static")

# Credentials for GCS (only load if using GCS)
if GS_BUCKET_NAME:
    GS_PROJECT_ID = os.getenv("GS_PROJECT_ID")  # optional
    cred_path = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
    if cred_path:
        GS_CREDENTIALS = service_account.Credentials.from_service_account_file(
            cred_path
        )

    # Django 5.1+ storage backend configuration
    # Use GCP for both media and static files (multi-tenant ready)
    STORAGES = {
        "default": {
            "BACKEND": "manage2soar.storage_backends.MediaRootGCS",
        },
        "staticfiles": {
            "BACKEND": "manage2soar.storage_backends.StaticRootGCS",
        },
    }

    GS_DEFAULT_ACL = os.getenv("GS_DEFAULT_ACL", "publicRead")

    # Multi-tenant GCP URLs
    if DEBUG:
        # Development: Serve static files locally
        STATIC_URL = f"/{CLUB_PREFIX}/static/"
        MEDIA_URL = f"/{CLUB_PREFIX}/media/"
    else:
        # Production: Serve static files from Google Cloud Storage
        MEDIA_URL = os.getenv(
            "MEDIA_URL",
            f"https://storage.googleapis.com/{GS_BUCKET_NAME}/{GS_MEDIA_LOCATION}/",
        )
        STATIC_URL = os.getenv(
            "STATIC_URL",
            f"https://storage.googleapis.com/{GS_BUCKET_NAME}/{GS_STATIC_LOCATION}/",
        )
else:
    # Local development without GCS - use Django's default file storage
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    STATIC_URL = "/static/"
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"

# Use TinyMCE JS from configured static storage
TINYMCE_JS_URL = os.getenv("TINYMCE_JS_URL", f"{STATIC_URL}tinymce/tinymce.min.js")

# Local static files directory (source for collectstatic)
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Note: Whitenoise completely removed - static files now served via GCP in production

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

# TIME_ZONE = "UTC"
TIME_ZONE = "America/New_York"
USE_TZ = True


USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTHENTICATION_BACKENDS = (
    "social_core.backends.google.GoogleOAuth2",
    "django.contrib.auth.backends.ModelBackend",
)


# ALLOWED_HOSTS configuration
# Multi-tenant system: Populated via DJANGO_ALLOWED_HOSTS environment variable
# The IaC deployment (Ansible) dynamically builds this from tenant domain configurations
# Never hardcode specific club domains here - breaks multi-tenant model
ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# Trust X-Forwarded-Proto header for HTTPS detection (required for OAuth2 redirect URI to use https)
# Only enable in production behind a reverse proxy (causes issues in development)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


#############################################################
# Email Configuration
#############################################################

# Mail server API key for fetching member lists
# Set this in production via environment variable
M2S_MAIL_API_KEY = os.getenv("M2S_MAIL_API_KEY", "")

# Email backend configuration
# In production, use SMTP2GO relay; in development, use console backend
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.getenv("EMAIL_HOST", "mail.smtp2go.com")
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() == "true"
    # Only set EMAIL_HOST_USER/PASSWORD if provided (trusted IP relay doesn't need auth)
    if os.getenv("EMAIL_HOST_USER"):
        EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
        EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
    # Email timeout in seconds (default 30, increased for slow mail servers)
    EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "30"))

# =============================================================================
# EMAIL DEV MODE - Safety valve for development/testing
# =============================================================================
# When enabled, ALL outgoing emails are redirected to configured test address(es).
# This prevents accidentally emailing real members during development.
#
# Set via environment variables:
#   EMAIL_DEV_MODE=true
#   EMAIL_DEV_MODE_REDIRECT_TO=developer@example.com[,other@example.com]
#
# Note: EMAIL_DEV_MODE works regardless of the DEBUG setting. However, when
# DEBUG=True, Django uses the console email backend which only prints emails
# to console (not sending them), so dev mode redirection has no practical
# effect in that case. EMAIL_DEV_MODE is primarily useful for staging/production
# environments where real SMTP is configured.
#
# Works independently of the mail server dev mode (which only affects
# mailing lists routed through Postfix). This catches ALL Django emails
# including direct send_mail() calls in management commands.
# =============================================================================
EMAIL_DEV_MODE = os.getenv("EMAIL_DEV_MODE", "false").lower() == "true"
EMAIL_DEV_MODE_REDIRECT_TO = os.getenv("EMAIL_DEV_MODE_REDIRECT_TO", "")

# Development vs Production URLs
if DEBUG:
    CSRF_TRUSTED_ORIGINS = ["http://127.0.0.1:8000", "http://localhost:8000"]
    SITE_URL = "http://127.0.0.1:8000"
else:
    CSRF_TRUSTED_ORIGINS = ["https://m2s.skylinesoaring.org"]
    SITE_URL = "https://m2s.skylinesoaring.org"

# Default sender address - can be overridden per-club via siteconfig
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@manage2soar.com")
EMAIL_SUBJECT_PREFIX = "[Manage2Soar] "

#############################################################
# Security Settings for Production Deployment
# These can be overridden via environment variables
#############################################################

# HTTPS Security Settings - Only enable in production
if not DEBUG:
    # HTTP Strict Transport Security (HSTS)
    # Only enable in production with HTTPS - prevents man-in-the-middle attacks
    # WARNING: Once enabled, this cannot be easily reversed!
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))  # 1 year
    if SECURE_HSTS_SECONDS > 0:
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True

    # Force HTTPS redirect - only enable in production
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "True").lower() in (
        "true",
        "1",
        "yes",
    )

    # Secure cookies - only sent over HTTPS
    SESSION_COOKIE_SECURE = os.getenv("SESSION_COOKIE_SECURE", "True").lower() in (
        "true",
        "1",
        "yes",
    )

    # Secure CSRF cookies - only sent over HTTPS
    CSRF_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", "True").lower() in (
        "true",
        "1",
        "yes",
    )

    # Secure kiosk cookies - only sent over HTTPS (Issue #364)
    KIOSK_COOKIE_SECURE = os.getenv("KIOSK_COOKIE_SECURE", "True").lower() in (
        "true",
        "1",
        "yes",
    )
else:
    # Development settings - disable all HTTPS enforcement
    SECURE_HSTS_SECONDS = 0
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    # KIOSK_COOKIE_SECURE should be True in production to prevent session hijacking
    # WARNING: Deploying with DEBUG=True in production will set this to False,
    # creating a security vulnerability. Middleware logs warnings if cookies are
    # sent over insecure connections.
    KIOSK_COOKIE_SECURE = False


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "social": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
        "duty_roster.generator": {
            "handlers": ["console"],
            "level": "WARNING",
        },
    },
}

handler403 = "members.views.custom_permission_denied_view"

TINYMCE_DEFAULT_CONFIG = {
    "relative_urls": False,  # prevent ugly ../../../ paths
    "remove_script_host": True,  # strip protocol+host from URLs
    # disable URL conversion to preserve user input (fixes issue #207)
    "convert_urls": False,
    "height": 500,
    "menubar": "file edit view insert format tools table help",
    "plugins": "image link media code lists table fullscreen advlist autolink anchor searchreplace visualblocks insertdatetime help wordcount",
    "toolbar": (
        "undo redo | blocks | bold italic underline | alignleft aligncenter alignright alignjustify | "
        "bullist numlist outdent indent | link image media insertpdf | table | code | fullscreen | help"
    ),
    "image_caption": True,
    "automatic_uploads": True,
    "file_picker_types": "image media",
    "media_live_embeds": True,
    # FIX FOR ISSUE #277 - YOUTUBE ERROR 153: Multiple approaches to ensure proper referrer policy
    # YouTube Error 153 occurs when referrer policy is too restrictive (e.g., 'no-referrer')
    # Using 'strict-origin-when-cross-origin' allows YouTube to verify the embedding domain
    # NOTE: These callbacks cannot be defined here as they require JavaScript functions.
    # They are defined in JavaScript that extends TinyMCE initialization.
    # See: static/js/tinymce-youtube-fix.js for the actual implementation
    "images_upload_url": "/members/tinymce-upload/",
    "images_upload_credentials": True,  # include CSRF token
    # Issue #322: Force tables to use responsive CSS by default
    "table_default_attributes": {"border": "1"},
    "table_default_styles": {
        "width": "100%",
        "max-width": "100%",
        "table-layout": "fixed",
    },
    # Use responsive sizing mode (replaces deprecated table_responsive_width)
    "table_sizing_mode": "responsive",
    "table_toolbar": (
        "tableprops cellprops | "
        "tableinsertrowbefore tableinsertrowafter tabledeleterow | "
        "tableinsertcolbefore tableinsertcolafter tabledeletecol"
    ),
    # Apply content CSS in the editor to match rendered output
    "content_style": """
        table { width: 100% !important; max-width: 100% !important; table-layout: fixed !important; }
        td, th { word-break: break-word; white-space: normal !important; }
        .pdf-container { margin: 1em 0; text-align: center; border: 1px solid #ddd; border-radius: 8px; padding: 10px; background-color: #f9f9f9; }
        .pdf-container iframe { max-width: 100%; border: none; border-radius: 4px; }
    """,
    # Issue #341: Extended valid elements to allow PDF embedding iframes
    # This ensures TinyMCE doesn't strip the iframe when saving
    "extended_valid_elements": (
        "iframe[src|width|height|frameborder|sandbox|referrerpolicy|loading|title|allow|allowfullscreen],"
        "div[class|style]"
    ),
    # Allow iframes inside div.pdf-container and p inside div
    "valid_children": "+div[iframe|p],+body[div]",
    "promotion": False,  # Disable TinyMCE 'Upgrade' button
    "license_key": "gpl",  # Use GPL license for open source projects
}

TEMPLATES[0]["OPTIONS"]["context_processors"].append(
    "notifications.context_processors.notifications"
)

TEMPLATES[0]["OPTIONS"]["context_processors"].append(
    "cms.context_processors.footer_content"
)

TEMPLATES[0]["OPTIONS"]["context_processors"].append(
    "duty_roster.context_processors.instructor_pending_requests"
)
