# Generated by Django 5.1.7 on 2025-03-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_alter_member_ssa_member_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="mobile_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
    ]
