# Generated by Django 5.2.6 on 2025-10-02 02:33

import utils.upload_entropy
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_pilot_certificate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.upload_entropy.upload_badge_image),
        ),
        migrations.AlterField(
            model_name='biography',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.upload_entropy.upload_biography),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.upload_entropy.upload_profile_photo),
        ),
    ]
