# Generated by Django 5.1.7 on 2025-03-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_alter_member_membership_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="is_assistant_duty_officer",
            new_name="assistant_duty_officer",
        ),
        migrations.RenameField(
            model_name="member",
            old_name="is_duty_officer",
            new_name="duty_officer",
        ),
        migrations.RenameField(
            model_name="member",
            old_name="is_instructor",
            new_name="instructor",
        ),
        migrations.AddField(
            model_name="member",
            name="director",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="member_manager",
            field=models.BooleanField(default=False),
        ),
    ]
