# Generated by Django 5.1.7 on 2025-03-24 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "members",
            "0006_rename_is_assistant_duty_officer_member_assistant_duty_officer_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Glider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("n_number", models.CharField(max_length=10, unique=True)),
                (
                    "competition_number",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                ("number_of_seats", models.PositiveIntegerField(default=1)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="glider_photos/"
                    ),
                ),
                (
                    "rental_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "max_rental_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="member",
            name="glider_owned",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_owners",
                to="members.glider",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="second_glider_owned",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secondary_owners",
                to="members.glider",
            ),
        ),
    ]
