# Generated by Django 5.1.7 on 2025-03-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_glider_alter_member_glider_owned_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="glider_rating",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("student", "Student"),
                    ("transition", "Transition"),
                    ("private", "Private"),
                    ("commercial", "Commercial"),
                ],
                default="student",
                max_length=10,
            ),
        ),
    ]
