# Generated by Django 5.1.7 on 2025-03-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0008_alter_member_glider_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="legacy_username",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
