# Generated by Django 5.2.8 on 2025-11-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0008_alter_member_membership_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="home_club",
            field=models.CharField(
                blank=True,
                help_text="Home soaring club or organization for visiting pilots",
                max_length=100,
                null=True,
            ),
        ),
    ]
