# Generated by Django 5.2.8 on 2025-11-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0009_add_home_club_field"),
    ]

    operations = [
        # Add index on SSA_member_number for efficient duplicate detection
        migrations.RunSQL(
            'CREATE INDEX IF NOT EXISTS members_member_ssa_member_number_idx ON members_member ("SSA_member_number");',
            reverse_sql="DROP INDEX IF EXISTS members_member_ssa_member_number_idx;",
        ),
        # Add composite index on (first_name, last_name) for efficient name-based duplicate detection
        migrations.RunSQL(
            'CREATE INDEX IF NOT EXISTS members_member_first_last_name_idx ON members_member ("first_name", "last_name");',
            reverse_sql="DROP INDEX IF EXISTS members_member_first_last_name_idx;",
        ),
    ]
