# Generated by Django 5.1.7 on 2025-03-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0010_badge_memberbadge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="badge_images/"),
        ),
    ]
