# Generated by Django 5.2.8 on 2025-11-17 14:34

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0010_add_visiting_pilot_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this application",
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("under_review", "Under Review"),
                            ("additional_info_needed", "Additional Information Needed"),
                            ("approved", "Approved"),
                            ("waitlisted", "On Waiting List"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        help_text="Current status of the application",
                        max_length=25,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the application was originally submitted",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the application was last modified",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the application was reviewed",
                        null=True,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="First name", max_length=150),
                ),
                (
                    "middle_initial",
                    models.CharField(
                        blank=True, help_text="Middle initial", max_length=2
                    ),
                ),
                ("last_name", models.CharField(help_text="Last name", max_length=150)),
                (
                    "name_suffix",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("Jr.", "Jr."),
                            ("Sr.", "Sr."),
                            ("II", "II"),
                            ("III", "III"),
                            ("IV", "IV"),
                            ("V", "V"),
                        ],
                        help_text="Name suffix",
                        max_length=10,
                    ),
                ),
                ("email", models.EmailField(help_text="Email address", max_length=254)),
                (
                    "phone",
                    models.CharField(
                        help_text="Phone number",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number",
                                regex="^\\+?[\\d\\s\\-\\(\\)\\.]+$",
                            )
                        ],
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(
                        blank=True,
                        help_text="Mobile phone number (optional)",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number",
                                regex="^\\+?[\\d\\s\\-\\(\\)\\.]+$",
                            )
                        ],
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(help_text="Street address", max_length=200),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True,
                        help_text="Apartment, suite, etc. (optional)",
                        max_length=200,
                    ),
                ),
                ("city", models.CharField(help_text="City", max_length=100)),
                ("state", models.CharField(help_text="State/Province", max_length=100)),
                (
                    "zip_code",
                    models.CharField(help_text="ZIP/Postal code", max_length=20),
                ),
                (
                    "country",
                    models.CharField(
                        default="USA", help_text="Country", max_length=100
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        help_text="Emergency contact full name", max_length=200
                    ),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(
                        help_text="Relationship to applicant", max_length=100
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        help_text="Emergency contact phone number",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number",
                                regex="^\\+?[\\d\\s\\-\\(\\)\\.]+$",
                            )
                        ],
                    ),
                ),
                (
                    "pilot_certificate_number",
                    models.CharField(
                        blank=True,
                        help_text="FAA pilot certificate number (if applicable)",
                        max_length=32,
                    ),
                ),
                (
                    "has_private_pilot",
                    models.BooleanField(
                        default=False, help_text="Private Pilot Certificate"
                    ),
                ),
                (
                    "has_instrument_rating",
                    models.BooleanField(default=False, help_text="Instrument Rating"),
                ),
                (
                    "has_commercial_pilot",
                    models.BooleanField(
                        default=False, help_text="Commercial Pilot Certificate"
                    ),
                ),
                (
                    "has_cfi",
                    models.BooleanField(
                        default=False, help_text="Certified Flight Instructor"
                    ),
                ),
                (
                    "has_cfii",
                    models.BooleanField(
                        default=False,
                        help_text="Certified Flight Instructor - Instrument",
                    ),
                ),
                (
                    "glider_rating",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("student", "Student"),
                            ("transition", "Transition"),
                            ("private", "Private Glider"),
                            ("commercial", "Commercial Glider"),
                        ],
                        default="none",
                        help_text="Current glider rating",
                        max_length=15,
                    ),
                ),
                (
                    "total_flight_hours",
                    models.PositiveIntegerField(
                        default=0, help_text="Total flight hours (all aircraft)"
                    ),
                ),
                (
                    "glider_flight_hours",
                    models.PositiveIntegerField(
                        default=0, help_text="Total glider flight hours"
                    ),
                ),
                (
                    "recent_flight_hours",
                    models.PositiveIntegerField(
                        default=0, help_text="Flight hours in the last 24 months"
                    ),
                ),
                (
                    "ssa_member_number",
                    models.CharField(
                        blank=True,
                        help_text="Soaring Society of America member number (if applicable)",
                        max_length=20,
                    ),
                ),
                (
                    "previous_club_memberships",
                    models.TextField(
                        blank=True,
                        help_text="List any previous soaring club memberships",
                    ),
                ),
                (
                    "insurance_rejection_history",
                    models.BooleanField(
                        default=False,
                        help_text="Have you ever been rejected for aviation insurance?",
                    ),
                ),
                (
                    "insurance_rejection_details",
                    models.TextField(
                        blank=True, help_text="If yes, please explain the circumstances"
                    ),
                ),
                (
                    "club_rejection_history",
                    models.BooleanField(
                        default=False,
                        help_text="Have you ever been rejected for club membership?",
                    ),
                ),
                (
                    "club_rejection_details",
                    models.TextField(
                        blank=True, help_text="If yes, please explain the circumstances"
                    ),
                ),
                (
                    "aviation_incidents",
                    models.BooleanField(
                        default=False,
                        help_text="Have you been involved in any aviation incidents or accidents?",
                    ),
                ),
                (
                    "aviation_incident_details",
                    models.TextField(
                        blank=True, help_text="If yes, please provide details"
                    ),
                ),
                (
                    "soaring_goals",
                    models.TextField(
                        help_text="What are your goals with soaring? What interests you about our club?"
                    ),
                ),
                (
                    "availability",
                    models.TextField(
                        blank=True,
                        help_text="When are you typically available for club activities? (days, times, seasons)",
                    ),
                ),
                (
                    "reference1_name",
                    models.CharField(
                        blank=True, help_text="Reference #1 name", max_length=200
                    ),
                ),
                (
                    "reference1_phone",
                    models.CharField(
                        blank=True, help_text="Reference #1 phone", max_length=20
                    ),
                ),
                (
                    "reference1_relationship",
                    models.CharField(
                        blank=True,
                        help_text="Relationship to reference #1",
                        max_length=100,
                    ),
                ),
                (
                    "reference2_name",
                    models.CharField(
                        blank=True, help_text="Reference #2 name", max_length=200
                    ),
                ),
                (
                    "reference2_phone",
                    models.CharField(
                        blank=True, help_text="Reference #2 phone", max_length=20
                    ),
                ),
                (
                    "reference2_relationship",
                    models.CharField(
                        blank=True,
                        help_text="Relationship to reference #2",
                        max_length=100,
                    ),
                ),
                (
                    "agrees_to_terms",
                    models.BooleanField(
                        default=False,
                        help_text="Applicant agrees to club terms and conditions",
                    ),
                ),
                (
                    "agrees_to_safety_rules",
                    models.BooleanField(
                        default=False,
                        help_text="Applicant agrees to follow all club safety rules",
                    ),
                ),
                (
                    "agrees_to_financial_obligations",
                    models.BooleanField(
                        default=False,
                        help_text="Applicant agrees to meet financial obligations",
                    ),
                ),
                (
                    "additional_comments",
                    models.TextField(
                        blank=True,
                        help_text="Any additional comments or information from the applicant",
                    ),
                ),
                (
                    "admin_notes",
                    tinymce.models.HTMLField(
                        blank=True,
                        help_text="Private notes for membership managers (not visible to applicant)",
                    ),
                ),
                (
                    "waitlist_position",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Position on the waiting list (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "member_account",
                    models.OneToOneField(
                        blank=True,
                        help_text="Member account created when application was approved",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="membership_application",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Member manager who reviewed this application",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Membership Application",
                "verbose_name_plural": "Membership Applications",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="members_mem_status_d09784_idx"
                    ),
                    models.Index(
                        fields=["submitted_at"], name="members_mem_submitt_f78e6f_idx"
                    ),
                    models.Index(fields=["email"], name="members_mem_email_ca0cd5_idx"),
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="members_mem_last_na_4a8816_idx",
                    ),
                ],
            },
        ),
    ]
