# Generated by Django 5.2.8 on 2025-11-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0011_add_membership_applications"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipapplication",
            name="previous_member_at_this_club",
            field=models.BooleanField(
                default=False,
                help_text="Have you ever been a member of this club before?",
            ),
        ),
        migrations.AddField(
            model_name="membershipapplication",
            name="previous_membership_details",
            field=models.TextField(
                blank=True,
                help_text="If yes, please provide details (approximate years, membership status when you left, etc.)",
            ),
        ),
    ]
