# Generated by Django 5.1.7 on 2025-03-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0011_alter_badge_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="towpilot",
            field=models.BooleanField(default=False),
        ),
    ]
