# Generated by Django 5.2.8 on 2025-11-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0012_add_previous_membership_check"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipapplication",
            name="glider_rating",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("student", "Student"),
                    ("transition", "Transition"),
                    ("private", "Private Glider"),
                    ("commercial", "Commercial Glider"),
                    ("foreign", "Foreign Pilot"),
                ],
                default="none",
                help_text="Current glider rating",
                max_length=15,
            ),
        ),
    ]
