# Generated by Django 5.2.8 on 2025-11-26 18:42

from django.db import migrations, models

import utils.upload_entropy


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0013_add_foreign_pilot_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="profile_photo_medium",
            field=models.ImageField(
                blank=True,
                help_text="200x200 square thumbnail for profile views",
                null=True,
                upload_to=utils.upload_entropy.upload_profile_photo_medium,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="profile_photo_small",
            field=models.ImageField(
                blank=True,
                help_text="64x64 square thumbnail for navbar and lists",
                null=True,
                upload_to=utils.upload_entropy.upload_profile_photo_small,
            ),
        ),
    ]
