# Generated by Django 5.1.7 on 2025-03-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0013_biography"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="membership_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Full Member", "Full Member"),
                    ("Student Member", "Student Member"),
                    ("Family Member", "Family Member"),
                    ("Founding Member", "Founding Member"),
                    ("Honorary Member", "Honorary Member"),
                    ("Introductory Member", "Introductory Member"),
                    ("SSEF Member", "SSEF Member"),
                    ("Inactive", "Inactive"),
                    ("Non-Member", "Non-Member"),
                    ("Probationary Member", "Probationary Member"),
                    ("Transient Member", "Transient Member"),
                    ("FAST Member", "FAST Member"),
                    ("Service Member", "Service Member"),
                ],
                default="Non-Member",
                max_length=20,
                null=True,
            ),
        ),
    ]
