# Generated by Django 5.1.7 on 2025-03-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0014_alter_member_membership_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="middle_initial",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="name_suffix",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="nickname",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
