# Generated by Django 5.2.8 on 2025-11-26 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0014_add_performance_indexes"),
        ("members", "0014_add_profile_photo_thumbnails"),
    ]

    operations = []
