# Generated by Django 5.1.7 on 2025-03-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0015_member_middle_initial_member_name_suffix_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="name_suffix",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("Jr.", "Jr."),
                    ("Sr.", "Sr."),
                    ("II", "II"),
                    ("III", "III"),
                    ("IV", "IV"),
                    ("V", "V"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
