# Generated by Django 5.2.9 on 2025-12-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0015_merge_20251126_1811"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="membership_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Charter Member", "Charter Member"),
                    ("Full Member", "Full Member"),
                    ("Probationary Member", "Probationary Member"),
                    ("FAST Member", "FAST Member"),
                    ("Introductory Member", "Introductory Member"),
                    ("Affiliate Member", "Affiliate Member"),
                    ("Family Member", "Family Member"),
                    ("Service Member", "Service Member"),
                    ("Student Member", "Student Member"),
                    ("Transient Member", "Transient Member"),
                    ("Emeritus Member", "Emeritus Member"),
                    ("Honorary Member", "Honorary Member"),
                    ("Inactive", "Inactive"),
                    ("Non-Member", "Non-Member"),
                    ("Pending", "Pending"),
                    ("Role Account", "Role Account"),
                    ("Deceased", "Deceased"),
                ],
                default="Non-Member",
                max_length=50,
                null=True,
            ),
        ),
    ]
