# Generated by Django 5.1.7 on 2025-03-26 03:55

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0016_alter_member_name_suffix"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="badge",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="badge",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="badge",
            name="description",
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
