# Generated by Django 5.2.9 on 2026-01-11 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0016_alter_member_membership_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="KioskToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        editable=False,
                        help_text="Cryptographic token for magic URL (~288 bits entropy, auto-generated)",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name (e.g., 'Club Laptop', 'Field Tablet')",
                        max_length=100,
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash of device characteristics (set on first use)",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to immediately revoke this token",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "landing_page",
                    models.CharField(
                        choices=[
                            ("logsheet:today", "Today's Logsheet"),
                            ("logsheet:index", "All Logsheets"),
                            ("duty_roster:my_duties", "Duty Roster"),
                            ("members:member_list", "Member List"),
                        ],
                        default="logsheet:today",
                        help_text="Page to redirect to after authentication",
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Admin notes about this token/device"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The role account this token authenticates as",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kiosk_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kiosk Token",
                "verbose_name_plural": "Kiosk Tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KioskAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_value",
                    models.CharField(
                        help_text="Token value attempted (for failed lookups)",
                        max_length=64,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_fingerprint", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("invalid_token", "Invalid Token"),
                            ("inactive_token", "Inactive Token"),
                            ("fingerprint_mismatch", "Fingerprint Mismatch"),
                            ("bound", "Device Bound"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.TextField(blank=True)),
                (
                    "kiosk_token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to="members.kiosktoken",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kiosk Access Log",
                "verbose_name_plural": "Kiosk Access Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
