# Generated by Django 5.2.9 on 2026-01-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0017_kiosk_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kiosktoken",
            name="landing_page",
            field=models.CharField(
                choices=[
                    ("logsheet:today", "Today's Logsheet"),
                    ("logsheet:index", "All Logsheets"),
                    ("duty_roster:my_duties", "Duty Roster"),
                    ("members:member_list", "Member List"),
                ],
                default="logsheet:index",
                help_text="Page to redirect to after authentication",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="kiosktoken",
            name="token",
            field=models.CharField(
                editable=False,
                help_text="Cryptographic token for magic URL (auto-generated, 64 chars = ~288 bits entropy from secrets.token_urlsafe(48))",
                max_length=64,
                unique=True,
            ),
        ),
    ]
