# Generated by Django 5.1.7 on 2025-03-26 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "members",
            "0018_remove_member_state_member_country_member_state_code_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Towplane",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("registration", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="FlightLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_date", models.DateField()),
                (
                    "field",
                    models.CharField(
                        help_text="Airfield identifier, e.g. KFRR, W99", max_length=10
                    ),
                ),
                ("takeoff_time", models.TimeField()),
                ("landing_time", models.TimeField()),
                ("flight_time", models.DurationField(help_text="Total time of flight")),
                (
                    "release_altitude",
                    models.PositiveIntegerField(
                        blank=True, help_text="In feet", null=True
                    ),
                ),
                (
                    "flight_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Solo", "Solo"),
                            ("Dual", "Dual"),
                            ("Checkride", "Checkride"),
                            ("Demo", "Demo"),
                            ("Other", "Other"),
                        ],
                        default="Solo",
                        max_length=20,
                    ),
                ),
                ("exception", models.TextField(blank=True)),
                (
                    "pays",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("all", "All"),
                            ("half", "Half"),
                            ("rental", "Rental"),
                            ("tow", "Tow"),
                        ],
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "alternate_payer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flights_paid",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "glider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="members.glider",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flights_instructed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "passenger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flights_passenger",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pilot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flights_flown",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "towpilot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flights_towed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "towplane",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="members.towplane",
                    ),
                ),
            ],
            options={
                "ordering": ["-flight_date", "takeoff_time"],
            },
        ),
    ]
