# Generated by Django 5.2.9 on 2026-01-29 03:44

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0018_change_kiosktoken_landing_page_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="safety_officer",
            field=models.BooleanField(
                default=False,
                help_text="Safety Officer/Coach - receives safety reports from members",
            ),
        ),
        migrations.CreateModel(
            name="SafetyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=False,
                        help_text="If true, reporter identity is hidden from all viewers",
                    ),
                ),
                (
                    "observation",
                    tinymce.models.HTMLField(
                        help_text="What did you observe? Describe the safety concern in detail."
                    ),
                ),
                (
                    "observation_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when the observation occurred (optional)",
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Location where the observation occurred (optional)",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewed", "Reviewed"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "officer_notes",
                    tinymce.models.HTMLField(
                        blank=True,
                        help_text="Internal notes for safety officers (not visible to reporter)",
                        null=True,
                    ),
                ),
                (
                    "actions_taken",
                    tinymce.models.HTMLField(
                        blank=True,
                        help_text="Description of actions taken to address the concern",
                        null=True,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Member who submitted the report (null if anonymous)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="safety_reports_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="safety_reports_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Safety Report",
                "verbose_name_plural": "Safety Reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
