# Generated by Django 5.2.9 on 2026-01-30 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0019_safety_reports"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="parent_badge",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent badge (e.g., FAI Silver for Silver Duration leg). When a member has earned the parent, legs are hidden on the badge board.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legs",
                to="members.badge",
            ),
        ),
    ]
