# Generated by Django 5.2.14 on 2026-05-21 23:06

import members.models
from django.db import migrations, models
from typing import Any, cast


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0021_setup_all_group_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="membership_status",
            field=models.CharField(
                blank=True,
                choices=cast(Any, members.models.get_membership_status_choices),
                default="Non-Member",
                max_length=50,
                null=True,
            ),
        ),
    ]
