# Generated by Django 5.1.7 on 2025-03-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0022_remove_flightlog_field_flightlog_airfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightlog",
            name="flight_time",
            field=models.DurationField(
                blank=True, help_text="Total time of flight", null=True
            ),
        ),
        migrations.AlterField(
            model_name="flightlog",
            name="landing_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="flightlog",
            name="takeoff_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
