# Generated by Django 5.2.14 on 2026-06-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0022_alter_member_membership_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="is_stats_monger",
            field=models.BooleanField(
                default=False,
                help_text="Allows the member to export raw flight statistics CSV dumps.",
            ),
        ),
    ]
