# Generated by Django 5.1.7 on 2025-03-27 03:22

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0023_alter_flightlog_flight_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("is_closed", models.BooleanField(default=False)),
                ("notes", tinymce.models.HTMLField(blank=True, null=True)),
                (
                    "airfield",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.airfield",
                    ),
                ),
                (
                    "assistant_duty_officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_duty_days",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "duty_officer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duty_days",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instructor_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instructors_primary",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instructor_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instructors_secondary",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "towpilot_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="am_towpilots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "towpilot_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pm_towpilots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
