# Generated by Django 5.1.7 on 2025-03-27 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0024_flightday"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flightday",
            name="assistant_duty_officer",
        ),
        migrations.RemoveField(
            model_name="flightday",
            name="instructor_1",
        ),
        migrations.RemoveField(
            model_name="flightday",
            name="instructor_2",
        ),
        migrations.RemoveField(
            model_name="flightday",
            name="towpilot_1",
        ),
        migrations.RemoveField(
            model_name="flightday",
            name="towpilot_2",
        ),
        migrations.AddField(
            model_name="flightday",
            name="assistant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flight_days_assist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="flightday",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flight_days_instructing",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="flightday",
            name="towpilot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flight_days_tow",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="flightday",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="flightday",
            name="duty_officer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flight_days_duty",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
