# Generated by Django 5.2.15 on 2026-08-16 16:26

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

MEMBERSHIP_STATUS_CHOICES_SNAPSHOT = [
    ("Associate Limited", "Associate Limited"),
    ("Life", "Life"),
    ("Senior Active", "Senior Active"),
    ("Pre-Solo Junior", "Pre-Solo Junior"),
    ("Collegiate", "Collegiate"),
    ("Junior", "Junior"),
    ("Charter Member", "Charter Member"),
    ("Full Member", "Full Member"),
    ("Probationary Member", "Probationary Member"),
    ("FAST Member", "FAST Member"),
    ("Introductory Member", "Introductory Member"),
    ("Affiliate Member", "Affiliate Member"),
    ("Family Member", "Family Member"),
    ("Service Member", "Service Member"),
    ("Student Member", "Student Member"),
    ("Associate Member", "Associate Member"),
    ("Guest", "Guest"),
    ("Transient Member", "Transient Member"),
    ("Emeritus Member", "Emeritus Member"),
    ("Honorary Member", "Honorary Member"),
    ("Founding Member", "Founding Member"),
    ("SSEF Member", "SSEF Member"),
    ("Temporary Member", "Temporary Member"),
    ("Inactive", "Inactive"),
    ("Non-Member", "Non-Member"),
    ("Pending", "Pending"),
    ("Role Account", "Role Account"),
    ("Deceased", "Deceased"),
]


class Migration(migrations.Migration):

    dependencies = [
        (
            "logsheet",
            "0030_rename_logsheet_fl_logshee_25df4a_idx_logsheet_fl_logshee_3a0b41_idx",
        ),
        ("members", "0025_backfill_group_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="membership_status",
            field=models.CharField(
                blank=True,
                choices=MEMBERSHIP_STATUS_CHOICES_SNAPSHOT,
                default="Non-Member",
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="VisitingPilotVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateField(default=datetime.date.today)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "logsheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visiting_pilot_visits",
                        to="logsheet.logsheet",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visiting_pilot_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Visiting Pilot Visit",
                "verbose_name_plural": "Visiting Pilot Visits",
                "ordering": ["-visit_date", "-created_at"],
            },
        ),
    ]
