# Generated by Django 5.1.7 on 2025-03-27 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0025_remove_flightday_assistant_duty_officer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flightday",
            old_name="date",
            new_name="flight_date",
        ),
    ]
