# Generated by Django 5.1.7 on 2025-03-29 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0026_rename_date_flightday_flight_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flightlog",
            name="airfield",
        ),
        migrations.RemoveField(
            model_name="flightlog",
            name="alternate_payer",
        ),
        migrations.RemoveField(
            model_name="flightlog",
            name="glider",
        ),
        migrations.RemoveField(
            model_name="flightlog",
            name="instructor",
        ),
        migrations.RemoveField(
            model_name="flightlog",
            name="passenger",
        ),
        migrations.RemoveField(
            model_name="flightlog",
            name="pilot",
        ),
        migrations.RemoveField(
            model_name="flightlog",
            name="towpilot",
        ),
        migrations.RemoveField(
            model_name="flightlog",
            name="towplane",
        ),
        migrations.DeleteModel(
            name="FlightDay",
        ),
        migrations.DeleteModel(
            name="FlightLog",
        ),
        migrations.DeleteModel(
            name="Towplane",
        ),
    ]
