# Generated by Django 5.2.14 on 2026-08-25 20:47

import django.core.validators
import django.db.models.deletion
import members.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_alter_member_membership_status_visitingpilotvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='contact_visibility',
            field=models.JSONField(blank=True, default=dict, help_text='Per-field contact sharing preferences: inherit, share, or hide.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_status',
            field=models.CharField(blank=True, choices=members.models.get_membership_status_choices, default='Non-Member', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Emergency contact full name (optional)', max_length=200),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='Emergency contact phone number (optional)', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?[\\d\\s\\-\\(\\)\\.]+$')]),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, help_text='Relationship to applicant (optional)', max_length=100),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(blank=True, max_length=100)),
                ('home_phone', models.CharField(blank=True, max_length=20)),
                ('mobile_phone', models.CharField(blank=True, max_length=20)),
                ('preferred_contact_method', models.CharField(blank=True, choices=[('home_phone', 'Home phone'), ('mobile_phone', 'Mobile phone'), ('email', 'Email'), ('other', 'Other')], max_length=20)),
                ('preferred_contact_details', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProfileInformationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('member_change', 'Member change'), ('staff_request', 'Staff request')], max_length=20)),
                ('requested_fields', models.JSONField(default=list)),
                ('reason', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('overdue_notified_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_values', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('completed', 'Completed'), ('declined', 'Declined'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_information_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_information_requests_created', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_information_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileInformationRequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='members.profileinformationrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='profileinformationrequest',
            index=models.Index(fields=['member', 'status'], name='members_pro_member__042d68_idx'),
        ),
        migrations.AddIndex(
            model_name='profileinformationrequest',
            index=models.Index(fields=['status', 'due_date'], name='members_pro_status_128d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='profileinformationrequestevent',
            index=models.Index(fields=['request', 'created_at'], name='members_pro_request_1e294c_idx'),
        ),
    ]
