# Generated by Django 5.1.7 on 2025-03-29 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0027_remove_flightlog_airfield_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Airfield",
        ),
    ]
