# Generated by Django for issue #1065.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0028_backfill_state_code_from_freeform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="glider_rating",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("student", "Student"),
                    ("sport", "Sport Pilot"),
                    ("transition", "Transition"),
                    ("private", "Private"),
                    ("commercial", "Commercial"),
                ],
                default="student",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="glider_rating",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("student", "Student"),
                    ("sport", "Sport Pilot"),
                    ("transition", "Transition"),
                    ("private", "Private Glider"),
                    ("commercial", "Commercial Glider"),
                    ("foreign", "Foreign Pilot"),
                ],
                default="none",
                help_text="Current glider rating",
                max_length=15,
            ),
        ),
    ]
