# Generated by Django 5.1.7 on 2025-03-29 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0001_initial"),
        ("members", "0029_remove_member_glider_owned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="glider_owned",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owners",
                to="logsheet.glider",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="second_glider_owned",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secondary_owners",
                to="logsheet.glider",
            ),
        ),
    ]
