# Generated by Django 5.1.7 on 2025-03-30 23:18

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0031_delete_glider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biography",
            name="content",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
