# Generated by Django 5.1.7 on 2025-03-31 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0032_alter_biography_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="biography",
            options={"verbose_name_plural": "Biographies"},
        ),
    ]
