# Generated by Django 5.1.7 on 2025-04-14 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0034_alter_member_membership_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="glider_owned",
        ),
        migrations.RemoveField(
            model_name="member",
            name="second_glider_owned",
        ),
    ]
