# Generated by Django 5.1.7 on 2025-04-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0035_remove_member_glider_owned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="rostermeister",
            field=models.BooleanField(default=False),
        ),
    ]
